README.md, core/pom.xml, core/src/main/java/tech/tablesaw/api/Table.java, core/src/main/java/tech/tablesaw/io/DataFrameReader.java, core/src/main/java/tech/tablesaw/io/csv/CsvReadOptions.java, core/src/test/java/tech/tablesaw/io/csv/CsvReaderTest.java
This deprecates 14 methods and adds 6 new ones. Hopefully it should make creating a table easier overall
Addresses https://github.com/jtablesaw/tablesaw/issues/80 and https://github.com/jtablesaw/tablesaw/issues/129
Looking at `CsvReaderTest` demonstrates calling the API
=> Fluent Table creation API

core/src/main/java/tech/tablesaw/api/DateColumn.java, core/src/test/java/tech/tablesaw/api/DateColumnTest.java
I realised that code I "refactored"  yesterday had a bug. Actually, I changed the logic so now it occurs more frequently. Because missing value for DateColumn is set to Integer.MIN_VALUE whenever there is such value in a column "min" method is returning it. Before it was doing so only when the first value was missing.
Now I've fixed it and added test for it.
=> Fix bug in min of DateColumn

core/src/main/java/tech/tablesaw/api/DoubleColumn.java, core/src/main/java/tech/tablesaw/api/FloatColumn.java, core/src/main/java/tech/tablesaw/api/IntColumn.java, core/src/main/java/tech/tablesaw/api/LongColumn.java, core/src/main/java/tech/tablesaw/api/NumericColumn.java, core/src/main/java/tech/tablesaw/api/ShortColumn.java, core/src/test/java/tech/tablesaw/api/DoubleColumnTest.java, core/src/test/java/tech/tablesaw/api/FloatColumnTest.java, core/src/test/java/tech/tablesaw/api/IntColumnTest.java, core/src/test/java/tech/tablesaw/api/LongColumnTest.java, core/src/test/java/tech/tablesaw/api/ShortColumnTest.java
This PR addresses part-1 of #237, `up-conversion`.
Up-sizing, for e.g. int to long,  will be used to enable operations between numeric types. The inverse operation, for e.g. long to int, is expected to be significantly lossy and is not implemented as part of this PR. 
See discussion in #236 for more details.
The following will be supported:
1. `ShortColumn`
1. `getInt()`
1. `getLong()`
1. `getFloat()`
1. `getDouble()`
1. `IntColumn`
1. `getLong()`
1. `getFloat()`
1. `getDouble()`
1. `LongColumn`
1. `getDouble()`
1. `FloatColumn`
1. `getDouble()`
=> Add up-conversion methods in numeric columns

core/src/test/java/tech/tablesaw/store/StorageManagerTest.java
the "/tmp/*"  file paths won't work on windows, uses System.getProperty("java.io.tmpdir") to get local temp dir and updated paths to use that prefix.
maven tests fail on windows because the hardcoded temp test folder is invalid on Win machines:
**fails:**  /tmp/foo
**works:** System.getProperty("java.io.tmpdir") + "/foo"
No unit test, but changes now compile and the new code passes the "mvn clean test" for me on Win7x64.  Would be good to have someone on linux run the tests as well (I don't have a linux box setup for java work)
=> Fix temp paths so testing works on windows in StorageManagerTest.java

core/src/main/java/tech/tablesaw/api/Table.java, core/src/test/java/tech/tablesaw/api/TableTest.java
Two new table functions remove a column by either name or column index and replace with the supplied column.
Added new functions to simplify replacing a column so you don't have to find the existing column, remove it, and append new column into previous location - it's all done for you so that the new column is a drop-in replacement of existing.
Now includes a unit test that creates a table with two cols, then replaces one of the cols with a 3rd col and verifies it worked OK.
=>  Add replaceColumn() to Table

core/src/main/java/tech/tablesaw/api/DoubleColumn.java, core/src/main/java/tech/tablesaw/api/FloatColumn.java, core/src/main/java/tech/tablesaw/api/IntColumn.java, core/src/main/java/tech/tablesaw/api/LongColumn.java, core/src/main/java/tech/tablesaw/api/ShortColumn.java, core/src/test/java/tech/tablesaw/api/DoubleColumnTest.java, core/src/test/java/tech/tablesaw/api/FloatColumnTest.java, core/src/test/java/tech/tablesaw/api/IntColumnTest.java, core/src/test/java/tech/tablesaw/api/LongColumnTest.java, core/src/test/java/tech/tablesaw/api/ShortColumnTest.java
- Added cumSum() to Double/Float/Int/Long/ShortColumns to replicate cumulative sum functionality in pandas, etc. that returns a new column with cumSum() applied to original column.
- Also had to add the isMissing() to IntColumn/LongColumn/ShortColumn to keep coding similar across all type implementations.
New functions added as described above
Yes, this new PR includes unit tests for all of the data types that compare function results to an expected result.
=> Add cumulative sum function to columns - cumSum()

core/src/main/java/tech/tablesaw/api/DoubleColumn.java, core/src/main/java/tech/tablesaw/api/LongColumn.java, core/src/test/java/tech/tablesaw/api/DoubleColumnTest.java, core/src/test/java/tech/tablesaw/api/LongColumnTest.java
This PR addresses part-2 of #237: a generic subtract method implementation for `LongColumn` and `DoubleColumn`.
`aLongColumn.subtract(aDoubleColumn)` should result in a `DoubleColumn`. This could be achieved by delegating the operation to `DoubleColumn`. 
See discussion in #236 for more details.
**This PR is not merge-ready**. The intent of this PR is to demo high level code flow. If the approach is approved, changes will be required in other numeric types. Moreover the identification of a `delegate` could be abstracted out and be used in all numeric types.
=> Allow subtract operation between all numeric types

core/src/main/java/tech/tablesaw/io/csv/CsvReadOptions.java, core/src/main/java/tech/tablesaw/io/csv/CsvReader.java, core/src/test/java/tech/tablesaw/io/csv/CsvReaderTest.java
Short names for months (pattern `MMM`) depends on the current locale if
the `DateTimeFormatter` is build without a specific one. So detecting
column types `LOCAL_DATE` and `LOCAL_DATE_TIME` on localized csv data is
not possible furthermore it fails if the default locale differs [1].
Use locale from `CsvReadOptions` to test data with a localized
`DateTimeFormatter` to detect column types.
Closes #224.
[1] #213 - failed 'DataFrameJoinerTest'
Add parameter `Locale` to `CsvReader`
* `detectColumnTypes`
* `detectedColumnTypes`
* `printColumnTypes`
* `detectType`
Expose `locale` on `CsvReadOptions`.
add tests to core/src/test/java/tech/tablesaw/io/csv/CsvReaderTest.java
* `testLocalDateDetectionEnglish`
* `testLocalDateTimeDetectionEnglish`
* …
=> apply locale when detecting column types on csv read

core/src/main/java/tech/tablesaw/api/Table.java, core/src/main/java/tech/tablesaw/columns/Column.java, core/src/main/java/tech/tablesaw/conversion/TableConverter.java, core/src/main/java/tech/tablesaw/table/Relation.java, core/src/main/java/tech/tablesaw/util/DoubleArrays.java, core/src/test/java/tech/tablesaw/api/TableTest.java, core/src/test/java/tech/tablesaw/conversion/TableConverterTest.java, core/src/test/java/tech/tablesaw/util/DoubleArraysTest.java
This makes using Tablesaw with Smile a bit smoother as described in https://github.com/jtablesaw/tablesaw/issues/280#issuecomment-403702698.
Converting to double arrays and matrices is super common. E.g.:
```
moneyball.numberColumn("RD").asDoubleArray()
moneyball.copy().retainColumns("W").asMatrix()
```
This PR provides a much simpler API for this common operation:
```
moneyball.asDoubleArray("RD")
moneyball.asMatrix("W")
```
=> Add convenience methods to convert to double arrays for easier usage with Smile

core/pom.xml, core/src/main/java/tech/tablesaw/conversion/TableConverter.java
Smile defines an `AttributeDataset`, which is essentially the same thing as a Tablesaw `Table`
A lot of Smile algorithms take `AttributeDataset` as input, so this will make it easier still to interface with Smile. The dependency is `optional` which means `Smile` should not be added to your classpath, but if you're using `Smile` already you can simply call `table.as().smileDataset(...)`
It will also let us support named variables. The `Attribute`s are essentially column metadata such as the variable name. In the next release of Smile, `OLS` will have an `AttributeDataset` constructor which solves the variable name problem with that algorithm. Once a release is cut, you can simply do `new OLS(table.as().smileDataset(...))`. Let me know if you encounter other algorithms which you think …
=> Provide converter to Smile's AttributeDataset

core/src/examples/java/tech/tablesaw/CrossTabsExample.java, core/src/main/java/tech/tablesaw/api/BooleanColumn.java, core/src/main/java/tech/tablesaw/api/ColumnType.java, core/src/main/java/tech/tablesaw/api/DateColumn.java, core/src/main/java/tech/tablesaw/api/DateTimeColumn.java, core/src/main/java/tech/tablesaw/api/StandardColumnType.java, core/src/main/java/tech/tablesaw/api/StringColumn.java, core/src/main/java/tech/tablesaw/api/Table.java, core/src/main/java/tech/tablesaw/api/TimeColumn.java, core/src/main/java/tech/tablesaw/columns/AbstractColumnType.java, core/src/main/java/tech/tablesaw/columns/ColumnTypeImpl.java, core/src/main/java/tech/tablesaw/columns/SkipColumnType.java, core/src/main/java/tech/tablesaw/columns/booleans/BooleanColumnType.java, core/src/main/java/tech/tablesaw/columns/dates/DateColumnType.java, core/src/main/java/tech/tablesaw/columns/datetimes/DateTimeColumnType.java, core/src/main/java/tech/tablesaw/columns/numbers/DoubleColumnType.java, core/src/main/java/tech/tablesaw/columns/strings/StringColumnType.java, core/src/main/java/tech/tablesaw/columns/times/TimeColumnType.java, core/src/main/java/tech/tablesaw/io/TypeUtils.java, core/src/main/java/tech/tablesaw/io/csv/CsvReader.java, core/src/main/java/tech/tablesaw/io/jdbc/SqlResultSetReader.java, core/src/main/java/tech/tablesaw/table/Relation.java, core/src/main/java/tech/tablesaw/table/Rows.java
Ben, if you could take a look when you some time, it would be greatly appreciated. Also LMK if it seems likely to break anything in client code. 
Thanks very much. 
This code makes ColumnType an interface so it will be easier to create new column types, and perhaps may be possible in the future for library users to add new column types specific to their needs.
Currently, this cannot be done because there are several key statements that switch on column type. It is a future enhancement to eliminate those switch statements by (if possible) moving the requisite logic to the column types.  This would be more object-oriented anyway
The interface subsumes most of the functionality of the enum it replaces, including implementations of methods like values() and valueOf() defined on Enum. The …
=> Made ColumnType an interface

beakerx/src/main/java/tech/tablesaw/beakerx/TablesawDisplayer.java, core/src/main/java/tech/tablesaw/api/BooleanColumn.java, core/src/main/java/tech/tablesaw/api/DateColumn.java, core/src/main/java/tech/tablesaw/api/DateTimeColumn.java, core/src/main/java/tech/tablesaw/api/DoubleColumn.java, core/src/main/java/tech/tablesaw/api/FloatColumn.java, core/src/main/java/tech/tablesaw/api/IntColumn.java, core/src/main/java/tech/tablesaw/api/LongColumn.java, core/src/main/java/tech/tablesaw/api/NumericColumn.java, core/src/main/java/tech/tablesaw/api/Table.java, core/src/main/java/tech/tablesaw/api/TimeColumn.java, core/src/main/java/tech/tablesaw/columns/Column.java, core/src/main/java/tech/tablesaw/io/csv/CsvReader.java, core/src/main/java/tech/tablesaw/io/csv/CsvWriter.java, core/src/main/java/tech/tablesaw/io/jdbc/SqlResultSetReader.java, core/src/main/java/tech/tablesaw/io/string/DataFramePrinter.java, core/src/main/java/tech/tablesaw/joining/DataFrameJoiner.java, core/src/main/java/tech/tablesaw/selection/BitmapBackedSelection.java, core/src/main/java/tech/tablesaw/table/Relation.java, core/src/main/java/tech/tablesaw/table/Rows.java, core/src/main/java/tech/tablesaw/table/StandardTableSliceGroup.java, core/src/main/java/tech/tablesaw/table/TableSlice.java, core/src/test/java/tech/tablesaw/SortTest.java, core/src/test/java/tech/tablesaw/aggregate/AggregateFunctionsTest.java, core/src/test/java/tech/tablesaw/api/BooleanColumnTest.java, core/src/test/java/tech/tablesaw/api/TableTest.java, core/src/test/java/tech/tablesaw/columns/times/LocalTimeFilterTest.java
Fixes https://github.com/jtablesaw/tablesaw/issues/343
- `Table.append` and `Rows` functionality now happens without auto-boxing
- Made `select` utilize primitives vs converting to strings and then parsing
- Joining now happens without auto-boxing or converting to strings and then parsing
- SQL reading now utilizes objects rather than converting to strings and then parsing
Covered by existing unit tests
=> More efficient setting of cell values

core/src/main/java/tech/tablesaw/conversion/SmileConverter.java, core/src/main/java/tech/tablesaw/conversion/TableConverter.java, core/src/main/java/tech/tablesaw/table/Relation.java
@jrvanalstine @lwhite1 this fixes https://github.com/jtablesaw/tablesaw/issues/393
I didn't realize when I originally implemented the `TableConverter` that it would require all classes to be present. I thought it would only require them to be present if the methods using them were called, but that's not true
I'm not sure about the API. Right now I have:
```
.as().doubleMatrix()
.smile().dataset()
```
Would something like the below be better?
```
.asMatrix().doubles()
.asSmile().dataset()
```
=> Move usage of classes from optional dependency to their own class

core/src/main/java/tech/tablesaw/io/csv/CsvReader.java
[X] Tick to sign-off your agreement to the [Developer Certificate of Origin (DCO) 1.1](https://developercertificate.org)
CSVParser columns size changed from 512 to Integer.MAX_VALUE
no need for unit tests in this case
=> fix for #395 It's impossible to parse CSV file with more than 512 columns

docs/contributing.md
=> Remove outdated reference to javafx eclipse plugin

jsplot/src/main/java/tech/tablesaw/plotly/api/Heatmap.java, jsplot/src/main/java/tech/tablesaw/plotly/traces/HeatmapTrace.java
Heatmap is broken. It was impossible to run HeatmapExample.
Also HeatmapTrace was not following other Trace API rules.
I renamed from ```HeatmapTrace.heatmapBuilder()``` to ```HeatmapTrace.builder()```
and changed the first argument from ```List<String>``` to ```Object[]```
and marked old APIs ```@Deprecated```.
=> Fix Heatmap

jsplot/src/main/java/tech/tablesaw/plotly/components/Page.java, jsplot/src/main/java/tech/tablesaw/plotly/components/TemplateUtils.java, jsplot/src/main/resources/page_template.html, jsplot/src/test/java/tech/tablesaw/components/TemplateUtilsTest.java, jsplot/src/test/java/tech/tablesaw/components/page_template.html, jsplot/src/test/java/tech/tablesaw/plotly/PageTest.java, jsplot/src/test/resources/tech/tablesaw/components/page_template.html
property.
Modified the template to support setting location of plotly js library, and Page and PageBuilder accordingly.
There are tests for both cases, the default and custom cases.
=> Issue 479 template customization

core/pom.xml, excel/pom.xml, html/pom.xml, json/pom.xml, jsplot/pom.xml, smile/pom.xml
OSGi bundles and Eclipse integration.
Shade configurations were updated/created in each module's pom.xml files.
I checked that the shaded jars were usable in the Eclipse integration.
=> Updated the shade configuration, so it creates jars that can be used for

core/src/main/java/tech/tablesaw/columns/dates/PackedLocalDate.java, core/src/main/java/tech/tablesaw/columns/datetimes/PackedLocalDateTime.java, core/src/test/java/tech/tablesaw/columns/datetimes/PackedLocalDateTimeTest.java
I'd like to remove these methods because they are unused and also because they rely on `ZoneId.systemDefault()` which will introduce problems by returning different results on different systems
N/A
=> Remove unused epoch conversion methods

core/src/main/java/tech/tablesaw/io/jdbc/SqlResultSetReader.java, core/src/test/java/tech/tablesaw/io/jdbc/SqlResultSetReaderTest.java
Closes https://github.com/jtablesaw/tablesaw/issues/519. Thanks @edgar131 for the report, investigation, and suggested solution
=> Workaround for precision of 0 when reading jdbc resultset

core/src/main/java/tech/tablesaw/api/Table.java, core/src/main/java/tech/tablesaw/joining/DataFrameJoiner.java, core/src/test/java/tech/tablesaw/joining/DataFrameJoinerTest.java
Renamed `join` to `joinOn` so that it can be easily called from Groovy. Because `Table` implements `Iterable`, Groovy's `Iterable.join` method clobbers our own. Renaming makes it much easier to use in BeakerX.
See my [post on StackOverflow](https://stackoverflow.com/questions/56401713/prevent-groovydefaultmethods-join-from-shadowing-join-method-of-java-class) for full details of the issue.
Updated existing unit tests
=> Rename join to joinOn to make it work in BeakerX

core/src/main/java/tech/tablesaw/api/DoubleColumn.java, core/src/main/java/tech/tablesaw/api/NumericColumn.java, core/src/test/java/tech/tablesaw/api/NumberColumnTest.java
I couldn't call `map` because it would result in a compilation error:
>The method map is ambiguous for the type DoubleColumn
It'd be nice to have a `map` method taking `DoubleUnaryOperator` to avoid auto-boxing, but then we'd have to remove the generic `map` on `Column`. The Java collections avoid auto-boxing and method collisions by having the `map` method on the `stream()`. We should probably do the same after https://github.com/vigna/fastutil/pull/120 is merged
Added a unit test
=> Remove duplicate map function

core/src/main/java/tech/tablesaw/api/Table.java, core/src/main/java/tech/tablesaw/conversion/smile/SmileConverter.java, core/src/test/java/tech/tablesaw/api/TableTest.java, core/src/test/java/tech/tablesaw/conversion/smile/SmileConverterTest.java
…column
There was a mistake when creating nominal attribute for smile, it uses the length of the original column and not the unique column. The issue is noticed when you have a reasonable dataset of say 10,000 records and you  are trying to use smile.feature.OneHotEncoder, it creates close to 16,000 columns after encoding from  an original 12 columns and sometimes leading to OutOfMemoryException. 
I added stratified sampling as well
For the nominal attribute creation, It already had a unit test  it
For the stratified sampling, I added a test **testStratifiesSampleSplit** to check the  that the proportion of foxes in the split table is equal to the proportion specified for the whole table.
=> Fixed Smile Nominal Attribute creation and added stratified sampling

core/src/main/java/tech/tablesaw/api/DoubleColumn.java, core/src/main/java/tech/tablesaw/columns/numbers/NumberFillers.java, core/src/test/java/tech/tablesaw/columns/numbers/NumberFillersTest.java
Now you can do `fillWith(1.0)` instead of `fillWith(() -> 1.0)`
Added a unit test
=> Add fillWith(double)

core/src/main/java/tech/tablesaw/columns/strings/ByteDictionaryMap.java, core/src/main/java/tech/tablesaw/columns/strings/IntDictionaryMap.java, core/src/main/java/tech/tablesaw/columns/strings/ShortDictionaryMap.java, core/src/test/java/tech/tablesaw/api/StringColumnTest.java
Implemented instance counting in all DictionaryMap implementations.
key/values are removed from all maps when value count reaches 0, so all operations based on these maps are always correct.
The only modified methods are set(), append() and clear(). There is no impact on other methods.
All count-based methods now uses the count map for performance.
Fixes #541 
Added unit tests showing previous issue with StringColumn unique values counting
* The new map member references the implementation used instead of the interface so we can use the addTo() method
* Now unused private contains() method was removed
=> Correct issue #541 : unique values in StringColumns

core/src/main/java/tech/tablesaw/joining/DataFrameJoiner.java, core/src/test/java/tech/tablesaw/joining/DataFrameJoinerTest.java
Fix joins when one or both tables only contains join columns. Fixes #381 
Added tests for 
* inner join where both tables contain single column
* inner join where only right table contains single column.
* inner join where both tables contain only join keys.
* outer join where right table contains single column.
=> Fix Inner Join when one table has a single column

core/src/main/java/tech/tablesaw/columns/AbstractColumn.java, core/src/test/java/tech/tablesaw/api/FloatColumnTest.java
Helps with #538
Added mapToType columns making it easier to map a column to a different type. Such as int -> LocalDate. The mapToType methods are a then wrapper onto the existing mapInto method.
Added unit tests for a single type. Can add unit tests for every type if needed.
=> Add mapToType Columns

core/src/main/java/tech/tablesaw/io/jdbc/SqlResultSetReader.java, core/src/test/java/tech/tablesaw/io/jdbc/SqlResultSetReaderTest.java, core/src/test/java/tech/tablesaw/util/TestDb.java
During my use of Tablesaw, I found that when reading from a database, if a nullable double/integer column contained a null, the default value would instead be read into the Table.  After inspecting SqlResultSetReader, I saw that it did not utilize resultSet.wasNull() on the primitive type columns.  I added a separate function to check .wasNull() and utilize column.appendMissing() if it returned true.
Thanks for the great library!  It has helped my work tremendously and I enjoy utilizing it.
I expanded SqlResultSetReaderTest.testSqlResultSetReader to include a test on another table ("NullValues" that I created in TestDb.java) that contained …
=> added null support for SqlResultSetReader

core/src/main/java/tech/tablesaw/table/TableSlice.java, core/src/test/java/tech/tablesaw/table/TableSliceTest.java
The column and columns methods on TableSlice are inconsistent. One was returning the entire source column the other was returning the view for that slice.
Fixed existing unit tests. No longer rely on reference equality.
=> Fix inconsistency between column and columns methods on TableSlice

core/src/main/java/tech/tablesaw/table/Relation.java, core/src/main/java/tech/tablesaw/table/TableSlice.java, core/src/test/java/tech/tablesaw/api/TableTest.java, core/src/test/java/tech/tablesaw/filters/TimeDependentFilteringTest.java
Change TableSliceGroup to iterate over Table rows.
Add MapTo[x] method to Abstract Relation class so they can be used by TableSlice and Table. 
Helps with #538 
If the implementation looks good I can update this PR to include other column types or send another PR.
Yes
=> Add mapToDoubleColumn on Table

core/src/main/java/tech/tablesaw/api/Row.java, core/src/main/java/tech/tablesaw/api/Table.java, docs/gettingstarted.md
This adds a rolling `stream(n)` method which allows us to do many different operations such as `forEach`, `map`, `filter`, `anyMatch`, `allMatch`, etc. on rolling groups of rows. `rollWithRows(Consumer<Row[]> rows, int n)` is the same as `stream(n).forEach(consumer)`, so I've deprecated it since it's the same thing, but less powerful
@ryancerf depending on which PR is merged first (i.e. this one or https://github.com/jtablesaw/tablesaw/pull/579) either you or I might need to rebase to put this method on `Relation`
Existing unit tests cover this functionality. They're effective too because they caught a bug in my initial implementation.
=> Add rolling stream method

json/src/main/java/tech/tablesaw/io/json/JsonReader.java, json/src/test/java/tech/tablesaw/io/json/JsonReaderTest.java
Fixes #588 
Checks whether a json key exists before getting attempting to get it. If the key does not exist add missing a value.
Yes
=> Fix NPE when reading json array with incomplete rows

core/src/main/java/tech/tablesaw/columns/datetimes/DateTimeColumnFormatter.java, core/src/test/java/tech/tablesaw/api/DateTimeColumnTest.java
DateTimeColumnFormatter is using TimeColumnType instead of DateTimeColumnType for checking missing values leading to incorrect identification of missing values by the formatter
Added a test of DateTimeColumn formatter including missing value
=> Corrected ColumnType used for checking missingValue in DateTimeColumnFormatter

core/src/main/java/tech/tablesaw/table/StandardTableSliceGroup.java, core/src/test/java/tech/tablesaw/aggregate/AggregateFunctionsTest.java, core/src/test/java/tech/tablesaw/api/TableTest.java, core/src/test/java/tech/tablesaw/table/TableSliceGroupTest.java
The current implementation of splitOn (which is used by summarize) makes a copy of the source table while sorting. Making unnecessary copies of tables is usually slow.
This PR.
* Implements a partitioning algorithm that does not rely on sort.
* Does not make an extra copy of the source table.
* Make the TableSlice's returned by StandardTableSliceGroup views of the original source table, not views of the sorted copy created during the implementation of TableSliceGroup. This is important for #582 
Please excuse the formatting changes. Makes it look like there are more diffs here than there really are.
Yes. Added tests. Fixed tests that relied on the order of TableSlices in TableSliceGroup.
=> Stop TableSliceGroup from making a copy of the source table while sorting.

core/src/main/java/tech/tablesaw/columns/AbstractColumn.java, core/src/main/java/tech/tablesaw/columns/Column.java, core/src/test/java/tech/tablesaw/api/DateTimeColumnTest.java, core/src/test/java/tech/tablesaw/api/NumberColumnTest.java
- asStringColumn now uses delegation to the source column getUnformattedString in order to manage missing values
- Added javadoc
- Added a couple of tests for DoubleColumn, IntColumn and DateTimeColumn with missing values
=> Implementation change of AbstractColumn.asStringColumn

core/src/main/java/tech/tablesaw/api/Table.java, core/src/main/java/tech/tablesaw/sorting/Sort.java, core/src/test/java/tech/tablesaw/SortTest.java
* Move Sort prefix logic (+, -) from Table to Sort, so it can be used elsewhere.
* Improve  error messages when the prefix is invalid or the column does not exist on the table.
Yes. Improved testing of error messages.
=> Move the Sort prefix logic from Table class to Sort class.

core/src/main/java/tech/tablesaw/io/csv/CsvWriteOptions.java, core/src/main/java/tech/tablesaw/io/csv/CsvWriter.java, core/src/test/java/tech/tablesaw/io/csv/CsvWriteOptionsTest.java
Options to ignore leading and trailing whitespaces added in CsvWriterOptions. Fix for issue #603.
No.
=> Ignore whitespaces option added in CsvWriterOptions.

core/src/main/java/tech/tablesaw/api/TextColumn.java
Convert the collection of Strings input into `TextColumn.isIn` to a HashSet. This should get better performance when the input list is large. Fixes #611 
No change in behavior.
=> Use HashSet for Textcolumn `isIn`

aggregate/pom.xml, core/pom.xml, core/src/main/java/tech/tablesaw/api/Row.java, core/src/main/java/tech/tablesaw/columns/AbstractColumnParser.java, core/src/main/java/tech/tablesaw/io/ColumnTypeDetector.java, core/src/test/java/tech/tablesaw/io/ColumnTypeDetectorTest.java, pom.xml
but doesn't implement the enhancement.
Empty columns, and columns where all rows sampled have missing values, will get the default type, usually StringColumn or TextColumn, rather than LocalDateTime.
=> fixes bug #623

core/pom.xml, pom.xml
Adds slf4j as a dependency for https://github.com/jtablesaw/tablesaw/issues/628. I didn't have anywhere obvious to use it, so it's currently unused. I'll leave it to you guys to figure out where to use it. I thought it might be helpful to contribute this part because I've spent a lot of time working with Java logging in the past and I sometimes see folks add unnecessary dependencies so wanted to help make sure we avoid that.
=> Add slf4j-api as a dependency

core/src/main/java/tech/tablesaw/analytic/AggregateFunction.java, core/src/main/java/tech/tablesaw/analytic/AggregateFunctions.java, core/src/main/java/tech/tablesaw/analytic/AnalyticQuery.java, core/src/main/java/tech/tablesaw/analytic/AnalyticQueryEngine.java, core/src/main/java/tech/tablesaw/analytic/AnalyticQuerySteps.java, core/src/main/java/tech/tablesaw/analytic/ArgumentList.java, core/src/main/java/tech/tablesaw/analytic/NumberingFunction.java, core/src/main/java/tech/tablesaw/analytic/NumberingFunctions.java, core/src/main/java/tech/tablesaw/analytic/WindowFrame.java, core/src/main/java/tech/tablesaw/analytic/WindowSlider.java, core/src/main/java/tech/tablesaw/analytic/WindowSpecification.java, core/src/test/java/tech/tablesaw/analytic/AnalyticAggregateFunctionsTest.java, core/src/test/java/tech/tablesaw/analytic/AnalyticQueryEngineTest.java, core/src/test/java/tech/tablesaw/analytic/AnalyticQueryTest.java, core/src/test/java/tech/tablesaw/analytic/ArgumentListTest.java, core/src/test/java/tech/tablesaw/analytic/WindowFrameTest.java
* Added first pass of JavaDoc.
* Made as many of the classes/methods package private as possible.
* Added comments explaining implementation.
* Implemented executeInPlace method.
* cleaned up sliding vs append windows. Do not allow append windows to override removeLeftMost.
* Use consistent naming for referring to left and right side of a window.
* Implemented remaining basic analytic functions min, mean and count
Continues work on #582 
Yes added and improved testing.
=> Clean up Analytic Functions

core/src/main/java/tech/tablesaw/api/Row.java, core/src/main/java/tech/tablesaw/columns/numbers/NumberMapFunctions.java, core/src/main/java/tech/tablesaw/columns/strings/StringMapFunctions.java, core/src/test/java/tech/tablesaw/api/NumericColumnTest.java, core/src/test/java/tech/tablesaw/api/StringColumnTest.java
=> added a few map functions and tests for same.

core/src/main/java/tech/tablesaw/api/BooleanColumn.java, core/src/main/java/tech/tablesaw/api/DateColumn.java, core/src/main/java/tech/tablesaw/api/DateTimeColumn.java, core/src/main/java/tech/tablesaw/api/DoubleColumn.java, core/src/main/java/tech/tablesaw/api/FloatColumn.java, core/src/main/java/tech/tablesaw/api/InstantColumn.java, core/src/main/java/tech/tablesaw/api/IntColumn.java, core/src/main/java/tech/tablesaw/api/LongColumn.java, core/src/main/java/tech/tablesaw/api/ShortColumn.java, core/src/main/java/tech/tablesaw/api/StringColumn.java, core/src/main/java/tech/tablesaw/api/TextColumn.java, core/src/main/java/tech/tablesaw/api/TimeColumn.java, core/src/test/java/tech/tablesaw/api/FloatColumnTest.java
I use Java 8 streams a lot. This makes column creation a bit easier
=> Column creation from streams

core/pom.xml, core/src/main/java/tech/tablesaw/io/Source.java, core/src/test/java/tech/tablesaw/examples/PopulationExample.java
Detects encodings for input text files when possible, and when no encoding is specifically provided as an argument. If the detection confidence is weak, it falls back on the system default charset.
This implementation adds a new dependency to Core, which is undesirable, but getting data into tablesaw correctly is arguably its most important function so I think it's worth it.
See above
No but there are numerous tests that exercise this functionality
=> partial implementation of #638

core/src/test/java/tech/tablesaw/columns/ColumnTest.java, core/src/test/java/tech/tablesaw/io/csv/CsvReaderTest.java
The remaining warnings are from tests of deprecated code, so they should continue to warn until the code is removed.
=> Clean up unnecessary deprecation and varargs warnings

core/src/main/java/tech/tablesaw/aggregate/AggregateFunctions.java, core/src/main/java/tech/tablesaw/columns/numbers/NumberRollingColumn.java
I wanted to this reproduce [this chart from a Quora answer](https://qph.fs.quoracdn.net/main-qimg-a1f8ef78c1f847a1743d328fe03fcfb9.webp)
Added both `stdDev` and `standardDeviation` since they were both present in `AggregateFunctions`. They both do the same thing. Should we just have one and deprecate the other or leave both?
=> Add standard deviation to rolling column

core/src/main/java/tech/tablesaw/api/Table.java, core/src/main/java/tech/tablesaw/columns/AbstractColumn.java
Most of our methods return copies of columns. That means whenever I want to edit a column in a table I have to call `replaceColumn`. This makes that easier.
Adds a method to allow you to do:
```
table.replaceColumn(table.column("monthlyPriceIndex").interpolate().backfill());
```
Instead of:
```
table.replaceColumn("monthlyPriceIndex", table.column("monthlyPriceIndex").interpolate().backfill());
```
=> Add new replaceColumn method

json/src/main/java/tech/tablesaw/io/json/JsonReadOptions.java, json/src/main/java/tech/tablesaw/io/json/JsonReader.java
Allow a JSON Pointer Expression in JsonReadOptions.path() which selects a subtree to load. This seems to allow easy parsing of more JSON files.
For example, you could have an object:
```
{ "title": "Hello",
"items": [...]
}
```
and parse it by specifying the "/items" path.
Manual test.
=> Reads a specific JSON subtree based on the JSON Pointer expression from path()

jsplot/src/main/java/tech/tablesaw/plotly/components/Config.java, jsplot/src/main/java/tech/tablesaw/plotly/components/Figure.java, jsplot/src/main/java/tech/tablesaw/plotly/components/Layout.java, jsplot/src/main/resources/config_template.html, jsplot/src/test/java/tech/tablesaw/plotly/components/ConfigTest.java
Plot.ly has a `config` argument ( https://plot.ly/javascript/configuration-options/ ) as the last argument to `Plotly.plot`. This has many options to customize the UI.
This PR adds the initial way of supporting this `config` object and adds the `displayModeBar` option.
Note that I've made `config` part of the `Layout` object. This isn't how Plot.ly does it but it seems convenient to have a single 'configuration object'. The `config` field is not saved to the context nor serialized to JS by `Layout`. It is the job of `Figure` to do that. If you don't like it I can remove this part.
Yes, a basic one.
=> Adds plotly config argument. Only config.displayModeBar

jsplot/src/main/java/tech/tablesaw/plotly/Utils.java, jsplot/src/test/java/tech/tablesaw/plotly/UtilsTest.java
The generated plot Javascript is not valid if any of the values has a quote ( `'` ) in it. This PR escapes quotes before generating the JS arrays.
Yes.
=> Escapes quotes when building Javascript string arrays from Java arrays

core/src/main/java/tech/tablesaw/io/FileReader.java, core/src/main/java/tech/tablesaw/io/csv/CsvReader.java, core/src/main/java/tech/tablesaw/io/fixed/FixedWidthReader.java, html/src/main/java/tech/tablesaw/io/html/HtmlReader.java
These methods make it possible for users to get the inferred column types and the column names for a data file.
Having this metadata can simplify the solution to some specialized automated file reading issues. .
loosened the access control and renaming of two previously hidden methods. 
no
=> Made two FileReader methods public (and changed their names for clarity)

core/src/main/java/tech/tablesaw/columns/Column.java, core/src/test/java/tech/tablesaw/columns/ColumnTest.java
This fixed issue #704 by updating the `Column.mapInto` javadoc.
It also adds two new `Column.map` methods which offer a way to append data to a newly created column. The output column is easily created/provided via a `Supplier` or `Function`.
Yes.
=> Updates the Column.mapInto javadoc and adds two new Column.map methods

jsplot/src/main/java/tech/tablesaw/plotly/components/Layout.java, jsplot/src/main/resources/layout_template.html, jsplot/src/test/java/tech/tablesaw/components/LayoutTest.java
Generate layout: autosize when set, don't generate width: / height: and let Plot.ly compute them.
Closes issue #712
Yes.
=> Adds LayoutBuilder.autosize and only generates width: or height: to Javascript if they have been actually set

core/src/main/java/tech/tablesaw/aggregate/AggregateFunctions.java, core/src/main/java/tech/tablesaw/aggregate/InstantAggregateFunction.java, core/src/main/java/tech/tablesaw/api/InstantColumn.java, core/src/test/java/tech/tablesaw/aggregate/AggregateFunctionsTest.java
What changed:
1) Fixed a bug in InstantColumn where min would be null if the first value in the column was missing.
2) Update AggregationFunctions to provide a minInstant, maxInstant method for rolling up InstantColumns
Yes: See AggregateFunctionsTest
=> Pr instant column min max

core/src/main/java/tech/tablesaw/api/NumericColumn.java, core/src/test/java/tech/tablesaw/api/NumericColumnTest.java
1. Added `autocorrelation()` in `NumericColumn` class. 
2. Two methods are added one with `lag` argument and one no arg
3. No argument `autocorrelation()` calculates autocorrelation with lag=1
4. Implementation follows `autocorr()` function of pandas. https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.Series.autocorr.html
5. Fixes #35 
Yes. Added in `NumericColumnTest`
=> Adds AutoCorrelation support

core/src/main/java/tech/tablesaw/api/StringColumn.java, core/src/test/java/tech/tablesaw/api/StringColumnTest.java
- [ X] Tick to sign-off your agreement to the [Developer Certificate of Origin (DCO) 1.1](https://developercertificate.org)
This is a pre-requisite for the larger change to change Relation.summary() to return a Table.
This changes the summary for the StringColumn to provide statistics in a fixed format. This is similar to the Python pandas implementation.
Added a test for summary
=> Change StringColumn summary to a more useful fixed format #718

docs-src/dist/userguide/importing_data.md, docs-src/main/userguide/importing_data.md, docs/userguide/importing_data.md
`CsvReadOptionsBuilder builder` appeared to be a typo for `CsvReadOptions.Builder builder` (add a dot between `Options` and `Builder`.) 
https://www.javadoc.io/static/tech.tablesaw/tablesaw-core/0.31.0/tech/tablesaw/io/csv/CsvReadOptions.html
No. The documentation examples seem to be untested. Is there a framework to test documentation examples?
=> Fix apparent typo in docs: CsvReadOptionsBuilder -> CsvReadOptions.Builder

docs-src/main/userguide/importing_data.md, docs/userguide/importing_data.md
updated formatting, corrected link and added example for excel reading
Not required
=> Doc changes to importing_data

jsplot/src/main/java/tech/tablesaw/plotly/components/Component.java, jsplot/src/main/java/tech/tablesaw/plotly/components/threeD/Scene.java, jsplot/src/test/java/tech/tablesaw/components/TemplateUtilsTest.java
Made Component.engine non-static and added a protected getter, for use in sub-classes, e.g. Scene. Un-disabled test method in TemplateUtilsTest
The existing test was un-disabled.
=> Made Component.engine non-static, fixes issue #761

jsplot/src/main/java/tech/tablesaw/plotly/api/TimeSeriesPlot.java, jsplot/src/test/java/tech/tablesaw/plotly/TimeSeriesTest.java
adding a method to create a time series using instants.
Note that this could have been done using the ScatterTrace code, so this is more a convenience than a 'fix'. 
=> 'fix' for issue 722

core/src/main/java/tech/tablesaw/api/BooleanColumn.java, core/src/test/java/tech/tablesaw/columns/ColumnTest.java, core/src/test/java/tech/tablesaw/columns/booleans/BooleanMapUtilsTest.java
The issue only affects boolean columns, as boolean columns were the only ones with an explicit equals method. This was removed to rely on identity.
I can't see a reason to not rely on identity here, but i'm open to feedback on this.
=> this is a fix for 689.

core/src/main/java/tech/tablesaw/io/csv/CsvWriteOptions.java, core/src/main/java/tech/tablesaw/io/csv/CsvWriter.java, core/src/test/java/tech/tablesaw/io/csv/CsvWriteOptionsTest.java, core/src/test/java/tech/tablesaw/io/csv/CsvWriterTest.java
Adds an option to CsvWriteOptions to specify that all fields should be quoted. The result is that all output is quoted, including column headers and any column data regardless of column type.
The implementation simply passes the arguments to the equivalent Univocity code, which does the rest.
=> Fixes issue 725

jsplot/src/main/java/tech/tablesaw/plotly/components/Domain.java, jsplot/src/main/java/tech/tablesaw/plotly/traces/PieTrace.java, jsplot/src/main/resources/pie_trace_template.html
Plotly supports pie chart [subplots](https://plot.ly/javascript/pie-charts/#pie-chart-subplots). This is doable by adding the `domain` info.
Manual testing. With this:
```java
PieTrace trace = PieTrace.builder(new Object[]{"A","B"}, new double[]{2.0, 1})
.domain(Domain.builder().row(0).column(0).build())
.build();
PieTrace trace2 = PieTrace.builder(new Object[]{"A","B"}, new double[]{12.0, 21})
.domain(Domain.builder().row(0).column(1).build())
.build();
PieTrace trace3 = PieTrace.builder(new Object[]{"A","B"}, new double[]{20.0, 10})
.domain(Domain.builder().row(1).column(1).build())
.build();
Layout layout = Layout.builder()
.grid(Grid.builder().rows(2).columns(2).build())
.build();
Figure f = new Figure(layout, trace, trace2, trace3);
```
we get this:
=> Adds domain to pie trace in order to support subplots

core/src/main/java/tech/tablesaw/api/BooleanColumn.java, core/src/main/java/tech/tablesaw/api/DateColumn.java, core/src/main/java/tech/tablesaw/api/DateTimeColumn.java, core/src/main/java/tech/tablesaw/api/DoubleColumn.java, core/src/main/java/tech/tablesaw/api/FloatColumn.java, core/src/main/java/tech/tablesaw/api/InstantColumn.java, core/src/main/java/tech/tablesaw/api/IntColumn.java, core/src/main/java/tech/tablesaw/api/LongColumn.java, core/src/main/java/tech/tablesaw/api/ShortColumn.java, core/src/main/java/tech/tablesaw/api/TimeColumn.java, core/src/main/java/tech/tablesaw/sorting/comparators/DescendingIntComparator.java, core/src/main/java/tech/tablesaw/sorting/comparators/DescendingLongComparator.java, core/src/main/java/tech/tablesaw/table/Relation.java, core/src/test/java/tech/tablesaw/api/DoubleColumnTest.java
Sorts the fastutil collections using the proper `sort` method and avoids accessing the backing array via `.elements()` since it will generally have invalid data or zeros in there.
Closes issue #775
Two tests, and everything existing still runs which is promising.
=> Sorts column data using fastutil .sort methods

core/src/main/java/tech/tablesaw/io/csv/CsvReadOptions.java, core/src/main/java/tech/tablesaw/io/csv/CsvReader.java, core/src/main/java/tech/tablesaw/io/csv/CsvWriteOptions.java, core/src/main/java/tech/tablesaw/io/csv/CsvWriter.java, core/src/test/java/tech/tablesaw/io/csv/CsvReaderTest.java
Closes https://github.com/jtablesaw/tablesaw/issues/771
Made `CsvReadOptions` and `CsvWriteOptions` use the same defaults. The options were nullable in `CsvReadOptions` and fell back to the univocity defaults whereas `CsvWriteOptions` was non-nullable and specified its own non-standard defaults. I changed `CsvWriteOptions` to be nullable and fallback to the univocity defaults.
Added a unit test
=> Standardize CSV escaping

core/src/main/java/tech/tablesaw/joining/DataFrameJoiner.java, core/src/test/java/tech/tablesaw/joining/DataFrameJoinerTest.java
Current behavior of tablesaw behaves like a right outer join or full outer join should behave if the left table is empty. Based on review of the source code, this appears to be the case because the normal termination for left outer join and inner join is within a loop over the rows of the first table. This commit handles the special case of an empty left table for left outer join and inner join, correctly returning an empty table with the appropriate columns.
Although it should be fairly simple to test this, I did not take the time to understand your testing framework and add a unit test.
=> Fix behavior of INNER and LEFT_OUTER joins with empty left table

core/src/main/java/tech/tablesaw/api/TimeColumn.java, core/src/test/java/tech/tablesaw/api/TimeColumnTest.java
Fixes #789 by converting java.sql.Time to java.time.LocalTime in TimeColumn's appendObj(obj).
Added four tests in TimeColumnTest, which are all green.
=> Converting Time to LocalTime in TimeColumn's appendObj()

jsplot/src/main/java/tech/tablesaw/plotly/api/BubblePlot.java
expose more configurable options for bubble plot.
=> expose more config for bubble plot

core/src/main/java/tech/tablesaw/table/TableSliceGroup.java, core/src/test/java/tech/tablesaw/table/TableSliceGroupTest.java
A precondition was removed from `tech.tablesaw.table.TableSliceGroup.aggregate(ListMultimap<String, AggregateFunction<?, ?>> functions)` such that the method no longer throws an `IllegalArgumentException` when the table is empty.
This PR has also been discussed in #785 
A unit test is included that makes sure that aggregations on an empty table can be done, that the resulting table is also empty and that the table has the expected number of columns.
See `tech.tablesaw.table.TableSliceGroupTest.aggregateWithEmptyResult()`
=> remove precondition on aggregate such that empty slices are allowed

core/src/main/java/tech/tablesaw/columns/Column.java, core/src/test/java/tech/tablesaw/columns/ColumnTest.java
This reverts commit 7516c614527e33699f9ced936f34387588c4ace0.
Commit 7516c614527e33699f9ced936f34387588c4ace0 changes the semantics of `map`. `map` appends while `mapInto` sets values.
In a project I have this pattern all over the place:
```java
DateTimeColumn update = t.dateTimeColumn("Last Update");
DateColumn date = update.map(d -> d.toLocalDate(), DateColumn::create);
```
the latest Tablesaw update breaks everything as it tries to set values into a column with no rows.
None.
=> Revert "Reduce code duplication"

saw/src/main/java/tech/tablesaw/io/saw/ColumnMetadata.java, saw/src/test/java/tech/tablesaw/io/saw/SawStorageTest.java
INSTANT cols were being read as DateTimeColumns.
Added a test for instant columns
Minor cleanup of some Saw test code
What was changed?
see above
Did you add a unit test? 
yes
=> fix for saw column type issue

jsplot/src/main/java/tech/tablesaw/plotly/api/CandlestickPlot.java, jsplot/src/main/java/tech/tablesaw/plotly/api/OHLCPlot.java, jsplot/src/main/java/tech/tablesaw/plotly/api/PricePlot.java, jsplot/src/test/java/tech/tablesaw/examples/TimeSeriesVisualizations.java
- [x Tick to sign-off your agreement to the [Developer Certificate of Origin (DCO) 1.1](https://developercertificate.org)
- Added the ability to display DateTime and Instant columns in OHLC and Candlestick charts. 
- Extracted common code into a new PricePlot class. 
- Added comments
Added to existing test code
=> Fix #804 ohlc and candlestick plots did not supt datetime cols

core/src/main/java/tech/tablesaw/aggregate/BooleanNumericFunction.java, core/src/test/java/tech/tablesaw/aggregate/AggregateFunctionsTest.java
Changed the `returnType()` of `BooleanNumericFunction` to `ColumnType.DOUBLE`. It was `null` before and would therefore cause a null pointer exception during aggregation.
Unit tests were added for the `BooleanNumericFunction` instances `proportionTrue` and `proportionFalse`. Furthermore, a test for said aggregate functions in the context of table summarization was added.
=> Fixes returnType() of BooleanNumericFunction

core/src/main/java/tech/tablesaw/columns/dates/DateMapFunctions.java, core/src/main/java/tech/tablesaw/columns/datetimes/DateTimeMapFunctions.java
function returns the year and week-of-year for date columns. the column headings erroneously identified the columns as year & month.
=> fixed column titles for yearWeek methods on date and datetime columns

core/src/test/java/tech/tablesaw/io/fixed/FixedWidthReaderTest.java
This is a test refactoring.
**Problem:**
The Sensitive Equality test smell occurs when the toString() method is used within a test method. Test methods verify objects by invoking the default toString() method of the object and comparing the output against a specific string. Changes to the implementation of toString() might result in failure.
**Solution:**
Instead of using the default array toString() implementation, transformed the object into an array and compared them with assertArrayEquals()
=> Test improvement: removed sensitive equality (test smell)

README.md
+ https://haifengl.github.io/smile/ now gives 404, so changing a dead link to https://haifengl.github.io
+ some white space clean up 
Tested in Firefox browser on Linux, link works.
=> Fix dead links to Smile

core/src/main/java/tech/tablesaw/api/BooleanColumn.java, core/src/test/java/tech/tablesaw/api/BooleanColumnTest.java
=> fix NPE that occurs when sorting a boolean column with missing values

core/src/main/java/tech/tablesaw/io/FileReader.java, core/src/main/java/tech/tablesaw/io/ReadOptions.java, core/src/main/java/tech/tablesaw/io/csv/CsvReadOptions.java, core/src/test/java/tech/tablesaw/io/csv/CsvReaderTest.java
Allows the user to specify that a file containing duplicate column names should be imported, with the duplicate names modified. Current behavior is to throw an exception, forcing the user to modify the file externally. 
yes
=> implemented optional renaming of duplicate columns

core/src/main/java/tech/tablesaw/api/DoubleColumn.java, core/src/main/java/tech/tablesaw/api/FloatColumn.java, core/src/main/java/tech/tablesaw/api/IntColumn.java, core/src/main/java/tech/tablesaw/api/LongColumn.java, core/src/main/java/tech/tablesaw/api/NumericColumn.java, core/src/main/java/tech/tablesaw/api/ShortColumn.java, core/src/main/java/tech/tablesaw/columns/numbers/NumberFilters.java, core/src/main/java/tech/tablesaw/filtering/DeferredNumberColumn.java, core/src/main/java/tech/tablesaw/filtering/NumberFilterSpec.java, core/src/test/java/tech/tablesaw/api/FloatColumnTest.java, core/src/test/java/tech/tablesaw/api/IntColumnTest.java, core/src/test/java/tech/tablesaw/api/LongColumnTest.java, core/src/test/java/tech/tablesaw/api/NumberColumnTest.java, core/src/test/java/tech/tablesaw/api/ShortColumnTest.java, core/src/test/java/tech/tablesaw/api/TableTest.java, jsplot/src/test/java/tech/tablesaw/examples/DotPlotExample.java
Breaking change. The old primitive version did not work (with most compilers). The old methods using object varargs isIn(Number... numbers) and isNotIn(Number... numbers) were replaced with Collection<Number> versions. 
This will break any code that used the Number varargs version, although it had a shaky implementation that probably didn't work for anything other than DoubleColumn. 
Moved the primitive version for double... to the DoubleColumn class.
Added similar primitive methods for the other numeric column types
Added tests
Fixed a test broken by the change
Yes
=> implemented fix for ambiguous method call exception

core/src/main/java/tech/tablesaw/api/Row.java, core/src/main/java/tech/tablesaw/api/Table.java
Row.getNumber() lacked the call to getIndex() that converts a nominal row number for a slice into the correct value in the backing table.
adds code that converts nominal row number into true row number in one method where it was missing. 
There's already one that covers this case, which gets executed now that the main code has been changed.
=> fix for bug.

core/src/main/java/tech/tablesaw/joining/DataFrameJoiner.java, core/src/test/java/tech/tablesaw/joining/DataFrameJoinerTest.java
Fix bug of leftOuter join when using multi-tables. Fixes #807 
Add 3 test tables to `DataFrameJoinerTest`.
Add 1 test `leftJoinStoreWithMultiTables` for left outer join with multi-tables.
Fix the incurrect test `leftOuterJoinWithDoubles4`.
=> Fix leftOuterJoin on multiple tables

core/src/main/java/tech/tablesaw/api/TextColumn.java, core/src/main/java/tech/tablesaw/columns/AbstractColumnParser.java, core/src/test/java/tech/tablesaw/api/StringColumnTest.java, core/src/test/java/tech/tablesaw/api/TextColumnTest.java
In TextColumn, calling appendCell(string, parser) failed because the results of the call to parser.parse(string) was passed to appendObj(), which called parse again, this time using the default parser. This is fixed.
This commit also makes it possible to directly set the missingValueStrings list in a custom parser.
see above
Tests were added for TextColumn and StringColumn, which already worked ok.
=> fix bug in appendCell that caused custom parser to be ignored

core/src/main/java/tech/tablesaw/api/DateColumn.java, core/src/main/java/tech/tablesaw/columns/ColumnFormatter.java, core/src/main/java/tech/tablesaw/columns/TemporalColumnFormatter.java, core/src/main/java/tech/tablesaw/columns/booleans/BooleanFormatter.java, core/src/main/java/tech/tablesaw/columns/dates/DateColumnFormatter.java, core/src/main/java/tech/tablesaw/columns/instant/InstantColumnFormatter.java, core/src/main/java/tech/tablesaw/columns/numbers/NumberColumnFormatter.java, core/src/main/java/tech/tablesaw/columns/strings/StringColumnFormatter.java, core/src/main/java/tech/tablesaw/columns/times/TimeColumnFormatter.java, core/src/main/java/tech/tablesaw/io/csv/CsvWriteOptions.java, core/src/main/java/tech/tablesaw/io/csv/CsvWriter.java, core/src/test/java/tech/tablesaw/io/csv/CsvWriterTest.java
Deprecated support in CsvWriter for writing Date and DateTime columns using Java's DateTimeFormatter directly.
Replaced them with a new option usePrintFormatters(Boolean) that tells CsvWriter to use any printFormatters defined on all types of columns, unifying the output created by printAll() and other toString() variations with the writing of delimited text files. The new approach also handles missing values flexibly.
If this looks ok, I will add support for the other file output types using WriteOptions: html, json, fixed-width. I'm not really sure how the excel writing works, and i'm happy that way.
The sonar failure is sonar being stupid. It says I should remove the deprecated code some day. Which is true, but not a failure or code-smell today. 
I added 10 tests
=> Printformatting

pom.xml
Corrected maven-surefire-plugin configuration: merged the 2 argLine tags.
Allows tests to run on systems with a different default locale.
No new tests. Previous tests now pass on systems with a different default locale.
=> Corrected surefire plugin argLine

core/src/main/java/tech/tablesaw/joining/DataFrameJoiner.java, core/src/test/java/tech/tablesaw/joining/DataFrameJoinerPerformanceTest.java, core/src/test/java/tech/tablesaw/joining/DataFrameJoinerTest.java
Fix #902 
1. `tech.tablesaw.joining.DataFrameJoiner#joinInternal` method
I add the logic to determine which table will be used to do row iteration when table1 and table2 have different sizes. If table1 has a larger size than table B, table2 will be used to do row iteration. It significantly improves performance when table1 is much larger than table2.
2.`tech.tablesaw.joining.DataFrameJoiner#createMultiColSelection` method
This method is to choose the columns of a table used as the join key.  Originally, only the left table is chosen, **while I add the method parameters `List<Integer> joinColumnIndexes`, so both tables can be chosen to generate the col key index to do join.** 
I added a test case called …
=> Improve innerJoin performance

.github/workflows/ci.yml, core/src/test/java/tech/tablesaw/analytic/AnalyticQueryTest.java, core/src/test/java/tech/tablesaw/api/TableTest.java, core/src/test/java/tech/tablesaw/io/DataFrameReaderTest.java, core/src/test/java/tech/tablesaw/io/csv/UnicodeBomHandlingTest.java, core/src/test/java/tech/tablesaw/table/TableSummaryTest.java, html/src/test/java/tech/tablesaw/io/html/HtmlWriterTest.java, jsplot/src/test/java/tech/tablesaw/components/LayoutTest.java, jsplot/src/test/java/tech/tablesaw/plotly/components/FigureTest.java, pom.xml
Fixes issue #441 allowing to build project with Windows and with systems that don't has en-US as default locale
Changes made:
- Changing hardcoded line separator for `System.lineSeparator()'. Except in HTML writer because Jsoup seems to use always Unix line separator.
- Putting all surefire args in one line because two didn't work and system locale was used.
- Changed mocked URLs because Inet URLs were used as if they were valid local filesystem urls.
- Disabled BOM test. I think that test being failing is correct, at least in systems that don't use UTF-8. I haven't seen any management of BOM in the `tablesaw` code, and `univocity` seems to manage BOM but only when a `File` is passed and not a `Reader` as `tablesaw` uses.
=> Fix #441 allowing to build project with Windows

core/src/main/java/tech/tablesaw/joining/DataFrameJoiner.java, core/src/test/java/tech/tablesaw/joining/DataFrameJoinerTest.java
Fix bug of multi-table rightOuter joining (issue #907). The solution is recomputing `joinColumnIndexes` after each iteration. 
BTW, I checked `fullOuter` joining as well and added some tests on it. It works well so far.
Added 5 new tests and modified 1 incorrect test.
=> Fix rightOuter joining  on multiple tables.

core/src/main/java/tech/tablesaw/io/FileReader.java, core/src/main/java/tech/tablesaw/io/ReadOptions.java, core/src/main/java/tech/tablesaw/io/csv/CsvReadOptions.java, core/src/test/java/tech/tablesaw/io/csv/CsvReaderTest.java
add ignoreInvalidRows option in `CsvReadOptions` and `ReadOptions`  to skip invalid csv rows
add 2 unit tests
=> Allow reading of malformed CSV

core/src/main/java/tech/tablesaw/api/BooleanColumn.java, core/src/main/java/tech/tablesaw/api/DateColumn.java, core/src/main/java/tech/tablesaw/api/DateTimeColumn.java, core/src/main/java/tech/tablesaw/api/DoubleColumn.java, core/src/main/java/tech/tablesaw/api/FloatColumn.java, core/src/main/java/tech/tablesaw/api/InstantColumn.java, core/src/main/java/tech/tablesaw/api/IntColumn.java, core/src/main/java/tech/tablesaw/api/LongColumn.java, core/src/main/java/tech/tablesaw/api/NumberColumn.java, core/src/main/java/tech/tablesaw/api/ShortColumn.java, core/src/main/java/tech/tablesaw/api/StringColumn.java, core/src/main/java/tech/tablesaw/api/TextColumn.java, core/src/main/java/tech/tablesaw/api/TimeColumn.java, core/src/main/java/tech/tablesaw/columns/AbstractColumn.java, core/src/main/java/tech/tablesaw/columns/Column.java, core/src/main/java/tech/tablesaw/columns/strings/AbstractStringColumn.java, core/src/test/java/tech/tablesaw/api/BooleanColumnTest.java, core/src/test/java/tech/tablesaw/api/DateColumnTest.java, core/src/test/java/tech/tablesaw/api/DateTimeColumnTest.java, core/src/test/java/tech/tablesaw/api/DoubleColumnTest.java, core/src/test/java/tech/tablesaw/api/FloatColumnTest.java, core/src/test/java/tech/tablesaw/api/InstantColumnTest.java, core/src/test/java/tech/tablesaw/api/IntColumnTest.java, core/src/test/java/tech/tablesaw/api/LongColumnTest.java, core/src/test/java/tech/tablesaw/api/ShortColumnTest.java, core/src/test/java/tech/tablesaw/api/StringColumnTest.java, core/src/test/java/tech/tablesaw/api/TextColumnTest.java, core/src/test/java/tech/tablesaw/api/TimeColumnTest.java
This PR fixes issue #927 with the following changes:
- This enhancement defines parser() and setParser() methods on the Column interface, and adds a parser argument to the AbstractColumn constructor.
- All column types have been updated to call super with the type-appropriate DEFAULT_PARSER, to preserve functional compatibility with prior releases.
- All column appendCell() methods now parse input using the parser field value, instead of a hardcoded DEFAULT_PARSER.
Added unit tests for simple override of parsing strategy for each column type.
=> Fixes #927 - Allow default parsing to be overridden per column.

core/src/main/java/tech/tablesaw/io/fixed/FixedWidthWriteOptions.java, core/src/main/java/tech/tablesaw/io/fixed/FixedWidthWriter.java, core/src/test/java/tech/tablesaw/io/fixed/FixedWidthWriterTest.java
Construct `FixedWidthWriterSettings` with `FixedWidthFields.columnSpecs` to assign it to `FixedWidthWriterSettings.fieldLengths`    
The corresponding issue is #942.
Yes.
=> Assign the value to FixedWidthWriterSettings.fieldLengths

jsplot/src/main/java/tech/tablesaw/plotly/api/ContourPlot.java, jsplot/src/main/java/tech/tablesaw/plotly/traces/ContourTrace.java, jsplot/src/test/java/tech/tablesaw/plotly/ContourTest.java
Support drawing contour plots in #508 by adding two files: `ContourPlot.java` and `ContourTrace.java`
Add three tests in `ContourTest.java`
1. `testAsJavascript` for `asJavascript` method in `ContourTrace.java`
2. `testContourTrace` for `ContourTrace.java` and draw a contour plot
3. `testContourPlot` for `create` method in `ContourPlot.java` and draw a contour plot
=> Add support for contour plots

core/src/main/java/tech/tablesaw/joining/DataFrameJoiner.java, core/src/test/java/tech/tablesaw/joining/DataFrameJoinerTest.java
**This is a feature related to issue #692.**
What was changed:
I added a set of interface with an additional parameter called  `keepAllJoinKeyColumns` :
- `  public Table rightOuter(
Table table2,
boolean allowDuplicateColumnNames,
boolean keepAllJoinKeyColumns,
String... col2Names) `
- `  public Table inner(
Table table2,
boolean allowDuplicateColumnNames,
boolean keepAllJoinKeyColumns,
String... col2Names) `
- `  public Table fullOuter(
Table table2,
boolean allowDuplicateColumnNames,
boolean keepAllJoinKeyColumns,
String... col2Names)`
- `  public Table leftOuter(
Table table2,
boolean allowDuplicateColumnNames,
boolean keepAllJoinKeyColumns,
String... col2Names) `
This will work when two tables are doing an outer join, and you want to modify the join key …
=> Add options for keep join keys in both table when appling outer join 

core/src/main/java/tech/tablesaw/io/WriteOptions.java, core/src/main/java/tech/tablesaw/io/csv/CsvWriteOptions.java, core/src/main/java/tech/tablesaw/io/csv/CsvWriter.java, core/src/main/java/tech/tablesaw/io/fixed/FixedWidthWriteOptions.java, core/src/main/java/tech/tablesaw/io/fixed/FixedWidthWriter.java, core/src/test/java/tech/tablesaw/io/DataFrameWriterTest.java, core/src/test/java/tech/tablesaw/io/fixed/FixedWidthWriterTest.java
Add a boolean attribute `autoclose` in `WriteOptions` and `Builder`, whose default value is true. When `Builder` is constructed with OutputStream or Writer, set `autoclose` as false. 
Corresponding issue is #750 
Yes. 2 unit tests for testing whether FileOutputStream and OutputStreamWriter close.
=> Support for not closing the output stream opened by user

jsplot/src/main/java/tech/tablesaw/plotly/api/ViolinPlot.java, jsplot/src/main/java/tech/tablesaw/plotly/traces/ViolinTrace.java, jsplot/src/main/resources/trace_template.html, jsplot/src/test/java/tech/tablesaw/plotly/ViolinTest.java
This is the fix for issue #509  
Two files are added: `ViolinPlot.java` and `ViolinTrace.java`. Also I modified the file `trace_template.html` so that violin plot can draw the inner box plot at the same time. Also, considering that the mean line of violin plot is also frequently used, it is also added into the `trace_template.html` but I comment the code (`context.put("meanLine", "{visible: true}")`) that draw the mean line in `ViolinTrace.java` because it doesn't perform well together with inner box plot. You can changed the code and style according to your preference.
Test is developed following the style of other plot tests.
=> Add support for violin plot

core/src/main/java/tech/tablesaw/api/Table.java
fix(table): method 'where' apply 2 times selection function
No
=> fix(table): method 'where' apply 2 times selection function

jsplot/src/main/java/tech/tablesaw/plotly/components/Annotation.java, jsplot/src/main/resources/annotation_template.html, jsplot/src/test/java/tech/tablesaw/components/AnnotationTest.java
I add basic support for annotation in plot.ly as issue #615 want. It can support most of apis in annotation. 
I write 2 tests for 2 conditions in [guideline of annotation](https://plotly.com/javascript/text-and-annotations) and both of them have past.
=> To support annotation in plot.ly javascript.

core/src/main/java/tech/tablesaw/api/Table.java
Parallel quick sort fails because Table Row is not thread safe.
One line change replacing one FastUtil sort algorithm with another
Did you add a unit test? No.
=> replace parallelQuickSort with mergeSort to fix issue #957.

core/src/main/java/tech/tablesaw/api/DoubleColumn.java, core/src/main/java/tech/tablesaw/api/FloatColumn.java, core/src/main/java/tech/tablesaw/api/IntColumn.java, core/src/main/java/tech/tablesaw/api/LongColumn.java, core/src/main/java/tech/tablesaw/api/NumberColumn.java, core/src/main/java/tech/tablesaw/api/ShortColumn.java, core/src/main/java/tech/tablesaw/columns/Column.java, core/src/main/java/tech/tablesaw/columns/numbers/NumberColumnFormatter.java, core/src/test/java/tech/tablesaw/columns/numbers/NumberColumnFormatterTest.java, core/src/test/java/tech/tablesaw/io/csv/CsvWriterTest.java
Missing values in numeric columns could not be formatted for print or writing to files
The getString() methods in numeric columns were modified as they were short-circuting the handling of missing values. NumberColumnFormatter was modified to have a ColumnType field so it could be do the proper missing value check.
=> Fix issue #974

core/src/main/java/tech/tablesaw/api/StringColumn.java, core/src/main/java/tech/tablesaw/api/TextColumn.java, core/src/test/java/tech/tablesaw/api/StringColumnTest.java, core/src/test/java/tech/tablesaw/api/TextColumnTest.java
This is essential due to a design issue where table slices convert string columns to text columns. This prevents the simple appending of some slices to a new table with the same structure as the original
Precondition check was broadened to include both types. A cast was removed.
Did you add a unit test? Yes.
=> Allow TextColumn to append StringColumns, and vice-versa

core/src/main/java/tech/tablesaw/table/SelectionTableSliceGroup.java, core/src/main/java/tech/tablesaw/table/StandardTableSliceGroup.java, core/src/main/java/tech/tablesaw/table/TableSlice.java, core/src/main/java/tech/tablesaw/table/TableSliceGroup.java, core/src/test/java/tech/tablesaw/table/TableSliceTest.java
StandardTableSliceGroups create tableSlices that can be reconverted to Tables with structures matching the original 
=> #982 Fix for undesirable use of TextColumns as String Columns when slices are converted back to tables.

core/src/main/java/tech/tablesaw/api/TextColumn.java, core/src/main/java/tech/tablesaw/table/SelectionTableSliceGroup.java, core/src/main/java/tech/tablesaw/table/StandardTableSliceGroup.java, core/src/main/java/tech/tablesaw/table/TableSlice.java, core/src/main/java/tech/tablesaw/table/TableSliceGroup.java, core/src/test/java/tech/tablesaw/table/TableSliceGroupTest.java, core/src/test/java/tech/tablesaw/table/TableSliceTest.java
- [x Tick to sign-off your agreement to the [Developer Certificate of Origin (DCO) 1.1](https://developercertificate.org)
avoids copying of text columns to stringColumns to use the original slice approach. In the new approach the bytes produced by each row in the text column are used. 
Did you add a unit test?  No. There is already a test
=> SliceGroup TextColumn handling revision 

core/src/main/java/tech/tablesaw/io/DataFrameWriter.java, core/src/main/java/tech/tablesaw/io/DataWriter.java, core/src/main/java/tech/tablesaw/io/Destination.java, core/src/main/java/tech/tablesaw/io/WriteOptions.java, core/src/main/java/tech/tablesaw/io/csv/CsvWriteOptions.java, core/src/main/java/tech/tablesaw/io/fixed/FixedWidthWriteOptions.java, core/src/main/java/tech/tablesaw/io/fixed/FixedWidthWriter.java, core/src/test/java/tech/tablesaw/api/TableTest.java, html/src/main/java/tech/tablesaw/io/html/HtmlWriter.java, json/src/main/java/tech/tablesaw/io/json/JsonWriter.java
IOException is caught and re-thrown as RuntimeIOException(e)
IOException is caught and re-thrown as RuntimeIOException(e)
Did you add a unit test? No.
=> Removed IOException from write interfaces

core/src/main/java/tech/tablesaw/analytic/AnalyticQueryEngine.java, core/src/main/java/tech/tablesaw/analytic/FunctionMetaData.java, core/src/main/java/tech/tablesaw/api/Table.java, core/src/test/java/tech/tablesaw/api/TableTest.java
Automatically fill empty columns to match the size of the table they are added to. Columns that are not empty must continue to match the size of the table when added as adding a 24 row column to a 23 row table is most likely a bug
Did you add a unit test? Yes.
=> Simplify adding new column to table

docs/userguide/ml/Moneyball Linear regression.md
- [ x] Tick to sign-off your agreement to the [Developer Certificate of Origin (DCO) 1.1](https://developercertificate.org)
First time contributor here. I was evaluating Tablesaw + Smile for use in a java-based course, along the way I realized that the Moneyball tutorial syntax was out of date. 
**What was changed:**
(1) Code snippets were updated to the newer/streamlined tablesaw syntax
(2) The section on adding the smile dependency was updated to include the gradle syntax, as well as a note on the need to have the tablesaw-core and tablesaw-jsplot dependancies with the relevant mvnrepository links. 
(3) Added a link to baseball.csv, as it is already in the tablesaw repo and was difficult to get from the linked online course. 
(4) Replaced " " in image URLs with …
=> Update moneyball tutorial

core/src/main/java/tech/tablesaw/api/Table.java
The method IntArrays.parallelQuicksort() was used in place of IntArrays:sort(), when the comparator is not Compartor<Row>. Row is not thread safe as it's basically a cursor that slides over the table's rows, and not an actual materialized row.
No.
=> reintroduce parallel sorting of table indices where it is safe to do so

core/src/main/java/tech/tablesaw/api/BooleanColumn.java, core/src/main/java/tech/tablesaw/api/DateColumn.java, core/src/main/java/tech/tablesaw/api/DateTimeColumn.java, core/src/main/java/tech/tablesaw/api/DoubleColumn.java, core/src/main/java/tech/tablesaw/api/FloatColumn.java, core/src/main/java/tech/tablesaw/api/InstantColumn.java, core/src/main/java/tech/tablesaw/api/IntColumn.java, core/src/main/java/tech/tablesaw/api/LongColumn.java, core/src/main/java/tech/tablesaw/api/ShortColumn.java, core/src/main/java/tech/tablesaw/api/StringColumn.java, core/src/main/java/tech/tablesaw/api/Table.java, core/src/main/java/tech/tablesaw/api/TextColumn.java, core/src/main/java/tech/tablesaw/api/TimeColumn.java, core/src/main/java/tech/tablesaw/columns/Column.java, core/src/main/java/tech/tablesaw/columns/strings/ByteDictionaryMap.java, core/src/main/java/tech/tablesaw/columns/strings/DictionaryMap.java, core/src/main/java/tech/tablesaw/columns/strings/IntDictionaryMap.java, core/src/main/java/tech/tablesaw/columns/strings/ShortDictionaryMap.java
added method to Column Interface for comparing values from two different rows for equality, used it to avoid auto-boxing
used fastutil classes to make a multi map so we don't auto-box row indexes and hash codes.
Did you add a unit test? No.
=> eliminated the auto boxing of table values and row numbers

core/pom.xml, docs-src/pom.xml, excel/pom.xml, html/pom.xml, json/pom.xml, jsplot/pom.xml, saw/pom.xml
Shade breaks module encapsulation and we want to move in the direction of support for Java modules
Removed shade plugin references from the 1.0 branch only.
=> removed shade plugin from 1.0 branch.

jsplot/pom.xml
Upgrade pebble 3.1.2 to 3.1.4 for vulnerability fix:
- [CVE-2019-19899](https://www.oscs1024.com/hd/MPS-2019-16801)
=> fix(sec): upgrade pebble to 3.1.4

core/src/main/java/tech/tablesaw/columns/dates/DateParser.java, core/src/main/java/tech/tablesaw/columns/datetimes/DateTimeParser.java, core/src/main/java/tech/tablesaw/columns/times/TimeParser.java, core/src/test/java/tech/tablesaw/api/DateColumnTest.java, core/src/test/java/tech/tablesaw/api/DateTimeColumnTest.java, core/src/test/java/tech/tablesaw/io/TypeUtilsTest.java, core/src/test/java/tech/tablesaw/io/csv/CsvReaderTest.java, core/src/test/java/tech/tablesaw/io/csv/CsvWriterTest.java
Through out the project DateTimeFormatter.ofPattern(pattern) is being used, This doesn't caters DateTime formats with alphabets like am/AM, pm/PM or Jan/JAN, Feb/FEB etc. And because of that some test cases were failing in `tablesaw-core`
So I used `parseCaseInsensitive` for taking care of such cases. 
I didn't added the test case, but ran `tablesaw-core` and all of them are working fine now.
=> 1202 fixed, by using parseCaseInsensitive() function

core/src/main/java/tech/tablesaw/io/FileReader.java
renameDuplicateColumnHeaders when allowDuplicateColumnNames is true is case sensitive which causes validateColumn(final Column<?> newColumn) to fail and throw IllegalArgumentException. 
Used toLowerCase while using HashMap.
Also thought of using treeMap, but get() in treeMap has timecomplexity of O(log(n))
No
=> Name to lowercase in renameDuplicateColumnHeaders

json/src/main/java/tech/tablesaw/io/json/JsonReader.java
Change HashSet to LinkedHashSet for preserving key order in JSON data
I want to read the following JSON, but after reading it and printing the table, the columns were unordered. However, I have made some changes so that the columns are now ordered.
```
String json =
"[{\"日期\":\"1991-04-03\",\"开盘\":49,\"收盘\":49,\"最高\":49,\"最低\":49,\"成交量\":1,\"成交额\":5000,\"振幅\":0,\"涨跌幅\":22.5,\"涨跌额\":9,\"换手率\":0},{\"日期\":\"1991-04-04\",\"开盘\":48.76,\"收盘\":48.76,\"最高\":48.76,\"最低\":48.76,\"成交量\":3,\"成交额\":15000,\"振幅\":0,\"涨跌幅\":-0.49,\"涨跌额\":-0.24,\"换手率\":0}]\n";
JsonReader jsonReader = new JsonReader();
Table table = jsonReader.read(Source.fromString(json));
System.out.println(table.print());
```
before:
```
成交量  |   最低    |   开盘    |   成交额   |   涨跌额   |   最高    |      日期      |  振幅 …
```
=> Change HashSet to LinkedHashSet for preserving key order in JSON data

core/src/main/java/tech/tablesaw/api/BooleanColumn.java
- Correct the documentation for the `create` method that takes a name and an initial size.  (This closes #1186.)
- Change "true" to "false" in the documentation for `proportionFalse()`.
=> Correct BooleanColumn documentation

json/pom.xml
Upgraded `json-flattener` dependency to latest version 0.16.4 to remove the critical vulnerability in 0.8.1 version from `commons-text` version 1.8.0
Did you add a unit test? No since this is dependency upgrade so no new unit test case is required.
=> Upgrading json-flattener version to latest 0.16.4 version

jsplot/src/main/resources/axis_template.html
What was changed:
fix axis_template.html: add comma to range
reference issue post: https://github.com/jtablesaw/tablesaw/issues/1192
summary: comma is not added to the body such that any html jsplot output using the range field fails to render, fix is just to add comma
Did you add a unit test? No, it is not necessary
=> fix axis_template.html: add comma to range

jsplot/src/main/java/tech/tablesaw/plotly/api/PricePlot.java, jsplot/src/test/java/tech/tablesaw/plotly/OchlTest.java, jsplot/src/test/java/tech/tablesaw/plotly/OhlcTest.java
Fixes erroneous use of `==` in PricePlot (issue #1237)
Yes
=> fixes erroneous use of `==` in PricePlot (issue #1237)

jsplot/src/main/java/tech/tablesaw/plotly/components/TickSettings.java, jsplot/src/main/resources/axis_template.html
In tablesaw-jsplot, `AxisSettings.{prefix|suffix|showPrefix|showSuffix}` were not used in `axis_template.html`, making them useless.
I updated the template to use these options, and also added a `format` option matching plotly's `tickformat`.
I also fixed the value for `DisplayRules.ALL` from 'outside' to 'all'
No new unit tests
=> Take prefix/suffix TickSettings into account and add format option

jsplot/src/main/java/tech/tablesaw/plotly/display/Browser.java
- [ X] Tick to sign-off your agreement to the [Developer Certificate of Origin (DCO) 1.1](https://developercertificate.org)
This pull request adds an 'open' action to the browse method. The browse method was previously not supported in xdg, so this change makes it possible to use the browse method on platforms that support xdg by using the action 'open'. 
https://wiki.archlinux.org/title/Xdg-utils
None.
=> Add an open action to browse method. 

core/src/main/java/tech/tablesaw/api/Table.java
The `dropMissing` parameter in `Table.melt` is defined as a `Boolean` but used and tested as a `boolean`. Changed to `boolean` to avoid potential NPE.
=> Table.melt method parameter changed from Boolean to boolean

core/src/main/java/tech/tablesaw/io/FileReader.java, core/src/test/java/tech/tablesaw/io/csv/CsvReaderTest.java
- Fix `CSVReaderTest.testEmptyFileHeaderEnabled` by enabling header - disabled header tested in `testEmptyFileHeaderDisabled`
- Fix `FileReader.getColumnNames` to not throw NPE when header is enabled and file is empty
Fixed one
=> Fix empty csv test

core/src/main/java/tech/tablesaw/columns/dates/PackedLocalDate.java
Avoid potential int overflow in PackedLocalDate.plusYears
No
=> Avoid potential int overflow

json/src/test/java/tech/tablesaw/io/json/JsonReaderTest.java
Test case in PR #1206 description added as a unit test
Yes
=> Add json test from #1206

core/src/main/java/tech/tablesaw/io/FileReader.java, core/src/test/java/tech/tablesaw/io/csv/CsvReaderTest.java
- Add test for #1197
- Code refactored to call toLowerCase() only once
Yes
=> Add test for #1197

.mvn/jvm.config
Added  maven jvm options file required for using the `git-code-format-maven-plugin` on Java 16+. See https://github.com/Cosium/git-code-format-maven-plugin?tab=readme-ov-file#jdk-16-peculiarities
To be tested on java 11
=> Add jvm config for maven required for java 16+

core/src/test/java/tech/tablesaw/api/TableTest.java
Fix previously missed formatting issues 
Not needed
=> Fix formatting

core/src/main/java/tech/tablesaw/api/Table.java, core/src/test/java/tech/tablesaw/api/TableTest.java
Fixed issue with `Table.dropDuplicateRows` described in #1296 by reverting to using a custom map instead of a set of rows.
Reported use case implemented as unit test. Added back testing of hash collision.
=> Fix drop duplicate rows
