jtablesaw/tablesaw

src/test/java/com/github/lwhite1/tablesaw/SortTest.java
src/test/java/com/github/lwhite1/tablesaw/TestData.java

just a quick PR to see you like this direction

Issue-15 idea for making it easy for tests to access test data; 

---

src/main/java/com/github/lwhite1/tablesaw/index/LongIndex.java
src/test/java/com/github/lwhite1/tablesaw/index/LongIndexTest.java

Adding LongIndex; it appears this would be part of https://github.com/lwhite1/tablesaw/issues/64

add LongIndex

---

src/main/java/com/github/lwhite1/tablesaw/store/StorageManager.java

Fixed exception "Unexpected internal error near index 1" when saving
table on windows

fix issue #92

---

pom.xml
src/test/java/com/github/lwhite1/tablesaw/io/jdbc/SqlResultSetReaderTest.java
src/test/java/com/github/lwhite1/tablesaw/util/TestDb.java

*also use H2 in memory database in the unit test
*add H2 database maven dependency

Turn the SqlResultSetReaderTest into more unit test

---

pom.xml
src/main/java/com/github/lwhite1/tablesaw/util/collections/IntTreeRangeSet.java

Fix for https://github.com/lwhite1/tablesaw/issues/119

Upgrade Guava

---

pom.xml
src/main/java/com/github/lwhite1/tablesaw/plotting/xchart/TablesawTheme.java

Fix for https://github.com/lwhite1/tablesaw/issues/121

Upgrade xchart

---

pom.xml

This will create all the javadocs in one directory by running `mvn javadoc:aggregate`

Create aggregated javadocs

---

core/src/test/java/tech/tablesaw/api/FloatColumnTest.java

Suppose to split solving #47 in separate pull requests for easier code reviews.
This PR covers:
* `convert`
* `summary`
* `stats`
* `top`
* `bottom`
Left `summary` and `stats` tests look simple. I think that more complex test logic must be inside `Stats` tests. If you think either, can also cover it in next PR-s

Some tests for FloatColumn #47

---

core/src/main/java/tech/tablesaw/api/FloatColumn.java
core/src/test/java/tech/tablesaw/api/FloatColumnTest.java

Fixing wrong FloatPredicate values for isPositive and isNonNegative in FloatColumn.java.

Fix | Wrong FloatPredicate values in FloatColumn.java.

---

core/src/main/java/tech/tablesaw/api/BooleanColumn.java
core/src/main/java/tech/tablesaw/api/CategoryColumn.java
core/src/main/java/tech/tablesaw/api/DateColumn.java
core/src/main/java/tech/tablesaw/api/DateTimeColumn.java
core/src/main/java/tech/tablesaw/api/DoubleColumn.java
core/src/main/java/tech/tablesaw/api/FloatColumn.java
core/src/main/java/tech/tablesaw/api/IntColumn.java
core/src/main/java/tech/tablesaw/api/LongColumn.java
core/src/main/java/tech/tablesaw/api/ShortColumn.java
core/src/main/java/tech/tablesaw/api/TimeColumn.java

related to #216 
I went through all the columns classes in tech.tablesaw.api and change add to set.

Change 'add' to 'set' in set methods of Columns

---

core/src/main/java/tech/tablesaw/index/DoubleIndex.java
core/src/test/java/tech/tablesaw/index/DoubleIndexTest.java

Add `DoubleIndex` to index double-precision 64-bit IEEE 754 floating
point columns.
Closes #162.

add `DoubleIndex`

---

core/src/main/java/tech/tablesaw/io/TypeUtils.java

Remove double added date time formatter `dt2`.

polish `TypeUtils#DATE_FORMATTER`

---

plot/src/main/java/tech/tablesaw/api/plot/TableView.java
plot/src/main/java/tech/tablesaw/plotting/fx/FxTable.java
plot/src/test/java/tech/tablesaw/api/plot/TableViewExample.java

Stick to the format used for all other JavaFX plots.
Add an example using tornadoes.

#218 Add a JavaFX TableView to display a Table.

---

core/src/main/java/tech/tablesaw/api/DoubleColumn.java
core/src/main/java/tech/tablesaw/api/FloatColumn.java
core/src/main/java/tech/tablesaw/api/IntColumn.java
core/src/main/java/tech/tablesaw/api/LongColumn.java
core/src/test/java/tech/tablesaw/api/DoubleColumnTest.java
core/src/test/java/tech/tablesaw/api/FloatColumnTest.java
core/src/test/java/tech/tablesaw/api/IntColumnTest.java
core/src/test/java/tech/tablesaw/api/LongColumnTest.java

Fixes #231. Fixes the for loop and adds a test for the column

Fix difference computation in LongColumn

---

core/src/main/java/tech/tablesaw/api/NumberColumn.java
core/src/main/java/tech/tablesaw/columns/numbers/NumberMapUtils.java
core/src/main/java/tech/tablesaw/columns/numbers/NumberReduceUtils.java
core/src/test/java/tech/tablesaw/api/NumberColumnTest.java
core/src/test/java/tech/tablesaw/selection/SelectionTest.java

Added support for 3 correlation calculations: Pearsons, Spearman, Kendall. 
Tests were added for each

Correlation

---

core/src/main/java/tech/tablesaw/api/BooleanColumn.java
core/src/main/java/tech/tablesaw/api/DateColumn.java
core/src/main/java/tech/tablesaw/api/DateTimeColumn.java
core/src/main/java/tech/tablesaw/api/NumberColumn.java
core/src/main/java/tech/tablesaw/api/StringColumn.java
core/src/main/java/tech/tablesaw/api/Table.java
core/src/main/java/tech/tablesaw/api/TimeColumn.java
core/src/main/java/tech/tablesaw/columns/AbstractColumn.java
core/src/main/java/tech/tablesaw/columns/Column.java
core/src/main/java/tech/tablesaw/columns/dates/DateMapUtils.java
core/src/main/java/tech/tablesaw/columns/datetimes/DateTimeMapUtils.java
core/src/main/java/tech/tablesaw/columns/numbers/NumberColumnFormatter.java
core/src/main/java/tech/tablesaw/columns/numbers/NumberMapUtils.java
core/src/main/java/tech/tablesaw/columns/numbers/NumberReduceUtils.java
core/src/main/java/tech/tablesaw/columns/times/TimeMapUtils.java
core/src/test/java/tech/tablesaw/TableFilteringTest.java

Extended Table API. 
-- (re) added the ability to select by row number, or range. 
-- Extended the options for selecting a random sample.
-- added the ability to to remove either rows or columns with missing values
- several

Table enhancements

---

core/src/main/java/tech/tablesaw/api/BooleanColumn.java
core/src/main/java/tech/tablesaw/api/DateColumn.java
core/src/main/java/tech/tablesaw/api/DateTimeColumn.java
core/src/main/java/tech/tablesaw/api/DoubleColumn.java
core/src/main/java/tech/tablesaw/api/NumberColumn.java
core/src/main/java/tech/tablesaw/api/TimeColumn.java
core/src/main/java/tech/tablesaw/columns/booleans/BooleanFillers.java
core/src/main/java/tech/tablesaw/columns/booleans/fillers/BooleanIterable.java
core/src/main/java/tech/tablesaw/columns/dates/DateFillers.java
core/src/main/java/tech/tablesaw/columns/datetimes/DateTimeFillers.java
core/src/main/java/tech/tablesaw/columns/datetimes/fillers/TemporalRangeIterable.java
core/src/main/java/tech/tablesaw/columns/numbers/NumberFillers.java
core/src/main/java/tech/tablesaw/columns/numbers/fillers/DoubleRangeIterable.java
core/src/main/java/tech/tablesaw/columns/times/TimeFillers.java
core/src/test/java/tech/tablesaw/columns/booleans/BooleanFillersTest.java
core/src/test/java/tech/tablesaw/columns/dates/DateFillersTest.java
core/src/test/java/tech/tablesaw/columns/datetimes/DateTimeFillersTest.java
core/src/test/java/tech/tablesaw/columns/numbers/NumberFillersTest.java
core/src/test/java/tech/tablesaw/columns/times/TimeFillersTest.java

Currently covered are columns for boolean, double, LocalDateTime, LocalDate and LocalTime.
All are based on the same API pattern, a filler interface that is implemented by the column, with fillWith methods for Iterators, Iterables and Suppliers. Default Iterables for ranges of each type (not boolean) is provided. The time-related columns also have static createWith methods for creating columns filled with a range, since these cannot be created with null as initial values.
There are tests for each column type and range Iterable.

API for filling columns.

---

core/pom.xml
core/src/main/java/tech/tablesaw/columns/Column.java
core/src/main/java/tech/tablesaw/columns/strings/StringMapFunctions.java
core/src/main/java/tech/tablesaw/columns/strings/StringPredicates.java
core/src/main/java/tech/tablesaw/io/ParsingUtils.java
core/src/main/java/tech/tablesaw/io/csv/CsvReadOptions.java
core/src/main/java/tech/tablesaw/io/csv/CsvReader.java
core/src/main/java/tech/tablesaw/io/csv/CsvWriteOptions.java
core/src/main/java/tech/tablesaw/io/csv/CsvWriter.java
core/src/main/java/tech/tablesaw/io/html/HtmlTableReader.java
core/src/main/java/tech/tablesaw/io/string/DataFramePrinter.java
core/src/main/java/tech/tablesaw/selection/BitmapBackedSelection.java
core/src/main/java/tech/tablesaw/table/RollingColumn.java
core/src/main/java/tech/tablesaw/util/LevenshteinDistance.java
core/src/main/java/tech/tablesaw/util/StringUtils.java
core/src/test/java/tech/tablesaw/TestData.java
core/src/test/java/tech/tablesaw/api/StringColumnTest.java
core/src/test/java/tech/tablesaw/api/TableTest.java
core/src/test/java/tech/tablesaw/filters/SearchPerformanceTest.java
core/src/test/java/tech/tablesaw/filters/TimeDependentFilteringTest.java
core/src/test/java/tech/tablesaw/io/csv/CsvReadPerformanceTest.java
core/src/test/java/tech/tablesaw/table/SliceBugTests.java
data/simple-data-sort_by_int_and_date_ascending.csv
data/simple-data-sort_by_int_and_date_descending.csv
data/simple-data-sort_by_int_ascending.csv
data/simple-data-sort_by_int_descending.csv
data/simple-data-with-canonical-date-format.csv
data/sorted-simple-data-iq-asceding-dob-descending.csv
data/unsorted-simple-data.csv

Replace OpenCSV with univocity
No

Univocity as replacement for OpenCSV

---

core/src/main/java/tech/tablesaw/aggregate/CountFunction.java
core/src/main/java/tech/tablesaw/aggregate/CrossTab.java
core/src/main/java/tech/tablesaw/aggregate/Summarizer.java
core/src/main/java/tech/tablesaw/api/Table.java
core/src/main/java/tech/tablesaw/columns/dates/DateMapFunctions.java
core/src/main/java/tech/tablesaw/columns/strings/StringMapFunctions.java
core/src/main/java/tech/tablesaw/conversion/TableConverter.java
core/src/main/java/tech/tablesaw/io/TypeUtils.java
core/src/main/java/tech/tablesaw/io/csv/CsvReader.java
core/src/main/java/tech/tablesaw/io/html/HtmlTableWriter.java
core/src/main/java/tech/tablesaw/io/jdbc/SqlResultSetReader.java
core/src/main/java/tech/tablesaw/joining/DataFrameJoiner.java
core/src/main/java/tech/tablesaw/sorting/SortUtils.java
core/src/main/java/tech/tablesaw/table/Relation.java
core/src/main/java/tech/tablesaw/table/RollingColumn.java
core/src/main/java/tech/tablesaw/table/StandardTableSliceGroup.java
core/src/main/java/tech/tablesaw/table/TableSlice.java
core/src/main/java/tech/tablesaw/table/TableSliceGroup.java
core/src/test/java/tech/tablesaw/TableFilteringTest.java
core/src/test/java/tech/tablesaw/aggregate/AggregateFunctionsTest.java
core/src/test/java/tech/tablesaw/api/TableTest.java
core/src/test/java/tech/tablesaw/api/TimeColumnTest.java
core/src/test/java/tech/tablesaw/columns/ColumnTest.java
core/src/test/java/tech/tablesaw/columns/numbers/NumberMapFunctionsTest.java
core/src/test/java/tech/tablesaw/io/html/HtmlTableWriterTest.java
core/src/test/java/tech/tablesaw/table/TableSliceTest.java

Fix majority of remaining generics warnings

---

core/src/main/java/tech/tablesaw/aggregate/AggregateFunction.java
core/src/main/java/tech/tablesaw/aggregate/AggregateFunctions.java
core/src/main/java/tech/tablesaw/aggregate/BooleanAggregateFunction.java
core/src/main/java/tech/tablesaw/api/BooleanColumn.java
core/src/main/java/tech/tablesaw/api/ColumnType.java
core/src/main/java/tech/tablesaw/api/DateColumn.java
core/src/main/java/tech/tablesaw/api/DateTimeColumn.java
core/src/main/java/tech/tablesaw/api/DoubleColumn.java
core/src/main/java/tech/tablesaw/api/StringColumn.java
core/src/main/java/tech/tablesaw/api/TimeColumn.java
core/src/main/java/tech/tablesaw/columns/Column.java
core/src/main/java/tech/tablesaw/columns/SkipColumnType.java
core/src/main/java/tech/tablesaw/io/csv/CsvReader.java
core/src/test/java/tech/tablesaw/columns/ColumnTest.java

This is an updated version of https://github.com/jtablesaw/tablesaw/pull/336 which doesn't autobox

Fix generics warnings

---

core/src/main/java/tech/tablesaw/columns/numbers/NumberIterator.java

Fix for https://github.com/jtablesaw/tablesaw/issues/346

Fix NumberIterator

---

core/src/examples/java/tech/tablesaw/CrossTabsExample.java
core/src/main/java/tech/tablesaw/api/Table.java
core/src/main/java/tech/tablesaw/io/string/DataFramePrinter.java
core/src/main/java/tech/tablesaw/table/Relation.java
core/src/test/java/tech/tablesaw/TableFilteringTest.java
core/src/test/java/tech/tablesaw/api/NumberColumnTest.java
core/src/test/java/tech/tablesaw/api/QueryHelperTest.java
core/src/test/java/tech/tablesaw/api/TimeColumnTest.java

Fix for https://github.com/jtablesaw/tablesaw/issues/357

Use formatted strings when printing table

---

core/src/main/java/tech/tablesaw/api/StringColumn.java
core/src/main/java/tech/tablesaw/api/TextColumn.java

Negated the valueIsMissing() check

make removeMissing() actually remove missing, rather than removing only non-missing, for StringColumn and TextColumn

---

core/src/main/java/tech/tablesaw/api/DateColumn.java
core/src/test/java/tech/tablesaw/io/jdbc/SqlResultSetReaderTest.java
core/src/test/java/tech/tablesaw/util/TestDb.java

Adds SQL date support. Fixes https://github.com/jtablesaw/tablesaw/issues/414
Expanded existing unit tests to cover date type

Add SQL date support

---

core/src/main/java/tech/tablesaw/api/StringColumn.java
core/src/test/java/tech/tablesaw/api/StringColumnTest.java

Before it was returning `[-127.0, -126.0, -125.0, -127.0, -124.0, -123.0, -122.0, -126.0]`. Now it's returning non-negative values starting from 0
Added a unit test

Nicer string to number encoding

---

core/src/main/java/tech/tablesaw/api/BooleanColumn.java
core/src/main/java/tech/tablesaw/api/DateColumn.java
core/src/main/java/tech/tablesaw/api/DateTimeColumn.java
core/src/main/java/tech/tablesaw/api/DoubleColumn.java
core/src/main/java/tech/tablesaw/api/NumberColumn.java
core/src/main/java/tech/tablesaw/api/Table.java
core/src/main/java/tech/tablesaw/api/TimeColumn.java
core/src/main/java/tech/tablesaw/table/Relation.java
core/src/test/java/tech/tablesaw/SortTest.java
core/src/test/java/tech/tablesaw/api/FloatColumnTest.java

Possibility of sorting on negative indices (the was a TODO comment) and tests to that method.
I have also done some refactoring.
Yes

Add sorting on negative indices + some refactoring

---

docs/gettingstarted.md
docs/userguide/BarsAndPies.md
docs/userguide/plotting.md

Closes https://github.com/jtablesaw/tablesaw/issues/453 & https://github.com/jtablesaw/tablesaw/issues/454
Changed name of Tornado file per request at https://github.com/jtablesaw/tablesaw/issues/454
Replaced usage of `out`, which appeared only once in docs. `System.out.println` is more common in the docs, so this standardizes how we were demonstrating printing output
There's probably more that needs to be updated, but this is a start
N/A

Documentation improvements

---

core/src/main/java/tech/tablesaw/api/TimeColumn.java
core/src/main/java/tech/tablesaw/columns/numbers/DoubleColumnType.java
core/src/main/java/tech/tablesaw/table/TableSliceGroup.java
core/src/test/java/tech/tablesaw/api/TimeColumnTest.java
core/src/test/java/tech/tablesaw/columns/ColumnTest.java
jsplot/src/main/java/tech/tablesaw/plotly/traces/TraceBuilder.java
jsplot/src/test/java/tech/tablesaw/examples/MultiPlotExample.java

Remove an unused method
Change some method modifiers
Declare fields at top of class

Minor cleanup to improve Codacy score

---

core/src/test/java/tech/tablesaw/io/csv/CsvReaderTest.java

@lwhite1 I think this is a new test, but let me know if it's duplicating an existing one

Line endings

---

docs/gettingstarted.md

missing quotes in the example code
Modify the document only so there is no need to add a test

docs: missing quotes in the example code

---

jsplot/src/main/java/tech/tablesaw/plotly/Plot.java
jsplot/src/main/resources/page_template.html

I added ```<meta charset="UTF-8">``` to page_template.html for non ascii characters support.

Add <meta charset="UTF-8">

---

core/src/main/java/tech/tablesaw/io/ReadOptions.java
core/src/main/java/tech/tablesaw/io/csv/CsvReadOptions.java
core/src/main/java/tech/tablesaw/io/csv/CsvReader.java
core/src/test/java/tech/tablesaw/io/csv/CsvReaderTest.java
data/with_comments.csv

I've added the ability to ignore commented lines starting with a specified prefix character.
This is a simple change that just exposes functionality already in CsvFormat. 
I've tested comments before the header and throughout the CSV file to make sure the shape of the file is correct and the commented out lines are ignored and don't affect any existing functionality.

Support comment character in CSV files

---

jsplot/src/main/java/tech/tablesaw/plotly/api/AreaPlot.java
jsplot/src/main/java/tech/tablesaw/plotly/api/BubblePlot.java
jsplot/src/main/java/tech/tablesaw/plotly/api/CandlestickPlot.java
jsplot/src/main/java/tech/tablesaw/plotly/api/Heatmap.java
jsplot/src/main/java/tech/tablesaw/plotly/api/Histogram.java
jsplot/src/main/java/tech/tablesaw/plotly/api/Histogram2D.java
jsplot/src/main/java/tech/tablesaw/plotly/api/LinePlot.java
jsplot/src/main/java/tech/tablesaw/plotly/api/OHLCPlot.java
jsplot/src/main/java/tech/tablesaw/plotly/api/PiePlot.java
jsplot/src/main/java/tech/tablesaw/plotly/api/ScatterPlot.java
jsplot/src/main/java/tech/tablesaw/plotly/api/TimeSeriesPlot.java
jsplot/src/main/java/tech/tablesaw/plotly/components/Layout.java

Added additional `builder` methods to speed `Layout.Builder` creation

Reduce code duplication

---

core/src/main/java/tech/tablesaw/io/csv/CsvReadOptions.java
core/src/main/java/tech/tablesaw/io/csv/CsvReader.java
core/src/test/java/tech/tablesaw/io/csv/CsvReaderTest.java

Closes https://github.com/jtablesaw/tablesaw/issues/486
Added a new unit test

Auto-detect CSV line endings

---

core/src/main/java/tech/tablesaw/io/csv/CsvReadOptions.java
core/src/main/java/tech/tablesaw/io/csv/CsvReader.java
core/src/test/java/tech/tablesaw/io/csv/CsvReaderTest.java

Reverts jtablesaw/tablesaw#488

Revert "Auto-detect CSV line endings"

---

core/pom.xml
core/src/main/java/tech/tablesaw/io/DataFrameReader.java
core/src/main/java/tech/tablesaw/io/ReadOptions.java
core/src/main/java/tech/tablesaw/io/fixed/FixedWidthReadOptions.java
excel/pom.xml
excel/src/main/java/tech/tablesaw/io/xlsx/XlsxReadOptions.java
html/pom.xml
html/src/main/java/tech/tablesaw/io/html/HtmlReadOptions.java
html/src/main/java/tech/tablesaw/io/html/HtmlTableReader.java
json/pom.xml
json/src/main/java/tech/tablesaw/io/json/JsonReadOptions.java
json/src/main/java/tech/tablesaw/io/json/JsonReader.java

Introduced `HtmlReadOptions` and `JsonReadOptions` allowing for greater configuration. E.g. we can now read html from a file instead of just from the web. This will also make it easier to build a registry for different reader types
Mostly covered by existing unit tests. Should add some tests for the html reader though. That wasn't possible before because it couldn't read from a local file, but now we can. However, I'll wait to do that in another PR because I'd also like to move the tests to live in the subprojects as suggested by hallvard

Introduce HtmlReadOptions and JsonReadOptions

---

core/src/test/java/tech/tablesaw/io/DataFrameWriterTest.java
core/src/test/java/tech/tablesaw/io/html/HtmlWriterTest.java
html/src/main/java/tech/tablesaw/io/html/HtmlWriteOptions.java
html/src/main/java/tech/tablesaw/io/html/HtmlWriter.java

Added the ability for user to override html element creation functionality
Moved existing unit test to `HtmlWriterTest` and created a new unit test there for the new functionality

Add a callback for creating HTML elements

---

core/src/test/java/tech/tablesaw/io/html/HtmlWriterTest.java
html/src/main/java/tech/tablesaw/io/html/HtmlWriter.java

removed special handling for camel and snake case in column names
updated existing test

removed camel case and underscore help from html writer

---

core/pom.xml
core/src/main/java/tech/tablesaw/api/Table.java

Closes https://github.com/jtablesaw/tablesaw/issues/503
It turns out reflections is unmaintained. I switched to another library, which is better maintained and solves the log issue
Covered by existing tests

Switch from reflections to classgraph

---

core/src/main/java/tech/tablesaw/io/ColumnTypeDetector.java
core/src/main/java/tech/tablesaw/io/FileReader.java
core/src/main/java/tech/tablesaw/io/ReadOptions.java
core/src/main/java/tech/tablesaw/io/TableBuildingUtils.java
core/src/main/java/tech/tablesaw/io/csv/CsvReadOptions.java
core/src/main/java/tech/tablesaw/io/csv/CsvReader.java
core/src/main/java/tech/tablesaw/io/fixed/FixedWidthReadOptions.java
core/src/main/java/tech/tablesaw/io/fixed/FixedWidthReader.java
core/src/test/java/tech/tablesaw/TableFilteringTest.java
core/src/test/java/tech/tablesaw/api/RowTest.java
core/src/test/java/tech/tablesaw/api/TableTest.java
core/src/test/java/tech/tablesaw/io/csv/CsvReaderTest.java
core/src/test/java/tech/tablesaw/io/fixed/FixedWidthReaderTest.java
excel/src/main/java/tech/tablesaw/io/xlsx/XlsxReadOptions.java
html/src/main/java/tech/tablesaw/io/html/HtmlReadOptions.java
json/src/main/java/tech/tablesaw/io/json/JsonReadOptions.java

Closes https://github.com/jtablesaw/tablesaw/issues/515

More configurable column type detection

---

core/src/main/java/tech/tablesaw/api/Table.java

Add a method to get a `Row`. Right now you can iterate over all of them, but I just want to grab one specific `Row`

Add method to get row

---

core/src/main/java/tech/tablesaw/api/ColumnType.java
core/src/main/java/tech/tablesaw/api/InstantColumn.java
core/src/main/java/tech/tablesaw/columns/datetimes/DateTimeFilters.java
core/src/main/java/tech/tablesaw/columns/datetimes/DateTimeMapFunctions.java
core/src/main/java/tech/tablesaw/columns/datetimes/DateTimePredicates.java
core/src/main/java/tech/tablesaw/columns/datetimes/PackedLocalDateTime.java
core/src/main/java/tech/tablesaw/columns/instant/InstantColumnFormatter.java
core/src/main/java/tech/tablesaw/columns/instant/InstantColumnType.java
core/src/main/java/tech/tablesaw/columns/instant/InstantParser.java
core/src/main/java/tech/tablesaw/columns/instant/PackedInstant.java
core/src/main/java/tech/tablesaw/columns/temporal/TemporalColumn.java
core/src/main/java/tech/tablesaw/columns/temporal/TemporalFillers.java
core/src/main/java/tech/tablesaw/columns/temporal/TemporalFilters.java
core/src/main/java/tech/tablesaw/columns/temporal/TemporalMapFunctions.java
core/src/main/java/tech/tablesaw/columns/temporal/TemporalPredicates.java
core/src/main/java/tech/tablesaw/columns/temporal/fillers/TemporalRangeIterable.java
core/src/main/java/tech/tablesaw/index/LongIndex.java
core/src/main/java/tech/tablesaw/io/jdbc/SqlResultSetReader.java
core/src/main/java/tech/tablesaw/joining/DataFrameJoiner.java
core/src/test/java/tech/tablesaw/columns/dates/DateFillersTest.java
core/src/test/java/tech/tablesaw/columns/datetimes/DateTimeFillersTest.java
core/src/test/java/tech/tablesaw/columns/times/TimeFillersTest.java

I refactored a lot of existing code from `LocalDateTime` into a new `temporal` package to reduce copy/pasted code. If we do end up deciding we want to add a `ZonedDateTime` hopefully it should help with that as well.
Closes https://github.com/jtablesaw/tablesaw/issues/516

Add InstantColumn

---

core/src/main/java/tech/tablesaw/api/Table.java
core/src/test/java/tech/tablesaw/api/TableTest.java

Make it easier to keep/drop the first/last n rows
E.g. before this PR I can do:
```
Table result = table.select("A", "B");
result = result.dropRange(result.rowCount() - 40, result.rowCount());
```
E.g. after this PR I can do:
```
Table result = table.select("A", "B").dropRange(-40);
```
Added new unit tests

Add new dropRange and inRange methods

---

core/src/main/java/tech/tablesaw/io/csv/CsvReadOptions.java
core/src/main/java/tech/tablesaw/io/csv/CsvReader.java
core/src/main/java/tech/tablesaw/io/csv/CsvWriteOptions.java

Closes https://github.com/jtablesaw/tablesaw/issues/535

Option for setting csv read quote escape char

---

core/src/main/java/tech/tablesaw/api/Table.java

Added `stream()` method. Deprecated some existing methods in favor of `stream()` with example usage
Unit tests already exist

Add stream() method to Table

---

README.md

The version number was getting outdated. This should make it so that we don't have to update with each release

Update Getting Started section of README

---

core/src/main/java/tech/tablesaw/api/Table.java
core/src/main/java/tech/tablesaw/io/DataFrameWriter.java

Fixed missing `throw` statements identified by SpotBugs
No, only private methods modified

Fixed missing throw statement

---

jsplot/src/main/java/tech/tablesaw/plotly/components/Axis.java
jsplot/src/main/java/tech/tablesaw/plotly/components/Figure.java
jsplot/src/main/java/tech/tablesaw/plotly/event/EventHandler.java
jsplot/src/main/java/tech/tablesaw/plotly/event/EventHandlerBody.java
jsplot/src/main/java/tech/tablesaw/plotly/event/HoverBroadcastBody.java
jsplot/src/main/java/tech/tablesaw/plotly/event/HoverEventHandler.java
jsplot/src/main/resources/axis_template.html
jsplot/src/main/resources/figure_template.html
jsplot/src/test/java/tech/tablesaw/examples/HoverBroadcastExample.java

- [ x] Tick to sign-off your agreement to the [Developer Certificate of Origin (DCO) 1.1](https://developercertificate.org)
Added 'domain' tag to Axis component for proportional control of sub plot sizing
Added new folder and package tech.tablesaw.plotly.event to hold classes related to event handlers.  Within that, added abstract classes to represent event handers, and event handler bodies.  And added concrete implementation of hover event handler and hover event broadcast body.
Modified the implementation of Figure to support the inclusion of event handlers.
Added HoverBroadcastExample.java in tech.tablesaw.examples to demonstrate a simple example of the new features.
Only the example was added.

add framework for processing plotly events

---

core/src/main/java/tech/tablesaw/api/BooleanColumn.java
core/src/main/java/tech/tablesaw/api/DoubleColumn.java
core/src/main/java/tech/tablesaw/api/FloatColumn.java
core/src/main/java/tech/tablesaw/api/IntColumn.java
core/src/main/java/tech/tablesaw/api/LongColumn.java
core/src/main/java/tech/tablesaw/api/ShortColumn.java
core/src/main/java/tech/tablesaw/columns/Column.java
core/src/test/java/tech/tablesaw/columns/ColumnTest.java

plus test, plus fix for a bug in a DoubleColumn.create()

Fix for Make it easier to work with missing data #564

---

core/pom.xml
core/src/main/java/tech/tablesaw/api/BooleanColumn.java
core/src/main/java/tech/tablesaw/api/DateColumn.java
core/src/main/java/tech/tablesaw/api/DateTimeColumn.java
core/src/main/java/tech/tablesaw/api/DoubleColumn.java
core/src/main/java/tech/tablesaw/api/InstantColumn.java
core/src/main/java/tech/tablesaw/api/IntColumn.java
core/src/main/java/tech/tablesaw/api/LongColumn.java
core/src/main/java/tech/tablesaw/api/ShortColumn.java
core/src/main/java/tech/tablesaw/api/StringColumn.java
core/src/main/java/tech/tablesaw/api/TextColumn.java
core/src/main/java/tech/tablesaw/api/TimeColumn.java
core/src/main/java/tech/tablesaw/columns/Column.java
core/src/main/java/tech/tablesaw/columns/dates/DateColumnType.java
core/src/main/java/tech/tablesaw/columns/datetimes/DateTimeColumnType.java
core/src/main/java/tech/tablesaw/columns/datetimes/DateTimeParser.java
core/src/main/java/tech/tablesaw/columns/strings/StringColumnType.java
core/src/main/java/tech/tablesaw/columns/strings/TextColumnType.java
core/src/main/java/tech/tablesaw/columns/times/TimeColumnType.java
excel/pom.xml
html/pom.xml
json/pom.xml
jsplot/pom.xml
jsplot/src/main/java/tech/tablesaw/plotly/api/AreaPlot.java
jsplot/src/test/java/tech/tablesaw/examples/AreaPlotExample.java
jsplot/src/test/java/tech/tablesaw/examples/ScatterLegendExample.java
jsplot/src/test/java/tech/tablesaw/examples/ScatterplotWithSpecificAxisRange.java
jsplot/src/test/java/tech/tablesaw/examples/TimeSeriesVisualizations.java
pom.xml

Invoke `google-java-format` automatically at compile time
Tested manually

Automatically run Google formatter at compile time

---

core/src/test/java/tech/tablesaw/api/NumberColumnTest.java
core/src/test/java/tech/tablesaw/api/StringColumnTest.java

Highlight difference between how StringColumn and NumberColumn handle counting missingValues
* StringColumn includes missingValues in countUnique.
* NumberColumn does not include missingValues in countUnique.
Closes #590. Contains a test showing the issue does not exist in master.
Yes. Only tests.

Add Count Unique Tests. 

---

core/src/main/java/tech/tablesaw/api/DoubleColumn.java
core/src/main/java/tech/tablesaw/api/FloatColumn.java
core/src/main/java/tech/tablesaw/api/IntColumn.java
core/src/main/java/tech/tablesaw/api/LongColumn.java
core/src/main/java/tech/tablesaw/api/ShortColumn.java
core/src/main/java/tech/tablesaw/api/TimeColumn.java
core/src/test/java/tech/tablesaw/api/BooleanColumnTest.java
core/src/test/java/tech/tablesaw/api/DateColumnTest.java
core/src/test/java/tech/tablesaw/api/DateTimeColumnTest.java
core/src/test/java/tech/tablesaw/api/InstantColumnTest.java
core/src/test/java/tech/tablesaw/api/NumberColumnTest.java
core/src/test/java/tech/tablesaw/api/StringColumnTest.java
core/src/test/java/tech/tablesaw/api/TextColumnTest.java
core/src/test/java/tech/tablesaw/api/TimeColumnTest.java

Make countUnique and unique include missing values for all column types. Fixes #594 
Yes.

Make countUnique and unique include missing values

---

core/src/main/java/tech/tablesaw/api/Table.java
core/src/main/java/tech/tablesaw/table/TableSlice.java

* Improve javadoc for Table#sortOn(key) and TableSlice#sortOn(key).
* Make TableSlice#sourceRowNumberIterator() private (This method is new since the last release. Not a breaking change)

Improve javaDoc for sortOn.

---

core/src/main/java/tech/tablesaw/api/StringColumn.java
core/src/main/java/tech/tablesaw/api/TextColumn.java
core/src/main/java/tech/tablesaw/columns/strings/AbstractStringColumn.java

Create abstract super class for text like columns. Move common methods to superclass.
I always struggle with naming. Let me know if you think of a better name than AbstractStringColumn.
Fixes #573
No. No change in behavior.

Create abstract super class for text like columns. Move common methods there.

---

core/src/test/java/tech/tablesaw/filters/TimeDependentFilteringTest.java

See https://github.com/jtablesaw/tablesaw/pull/579#discussion_r314989878 for discussion

Remove unused variables

---

core/src/main/java/tech/tablesaw/api/Row.java
core/src/test/java/tech/tablesaw/api/RowTest.java

Fixes #617
New Error Msgs look like:
For missing column:
```
Column col2 is not present in table myTable
```
For using wrong type.
```
Column col1 is of type LOCAL_DATE and cannot be cast to LOCAL_TIME. Use the method for LOCAL_DATE.
```
Yes. Added tests.

Provide more helpful error messages when a column cannot be found on Row

---

docs/README.md
docs/gettingstarted.md
docs/tutorial.md
docs/userguide/importing_data.md
docs/userguide/toc.md

minor documentation improvements

---

core/src/main/java/tech/tablesaw/api/Row.java
core/src/test/java/tech/tablesaw/api/RowTest.java

add isMissing and setMissing methods to Row.
added double: getNumber() method to row. Returns a double for any numeric column, with requiring the user to specify the column type. 
Did you add a unit test? yes

Added missing value handling and getNumber() method  to Row.

---

core/src/main/java/tech/tablesaw/api/BooleanColumn.java
core/src/main/java/tech/tablesaw/api/DateColumn.java
core/src/main/java/tech/tablesaw/api/DateTimeColumn.java
core/src/main/java/tech/tablesaw/api/DoubleColumn.java
core/src/main/java/tech/tablesaw/api/FloatColumn.java
core/src/main/java/tech/tablesaw/api/InstantColumn.java
core/src/main/java/tech/tablesaw/api/IntColumn.java
core/src/main/java/tech/tablesaw/api/LongColumn.java
core/src/main/java/tech/tablesaw/api/ShortColumn.java
core/src/main/java/tech/tablesaw/api/StringColumn.java
core/src/main/java/tech/tablesaw/api/TextColumn.java
core/src/main/java/tech/tablesaw/api/TimeColumn.java

Undo deprecation missing value methods

---

core/src/main/java/tech/tablesaw/io/Source.java
core/src/test/java/tech/tablesaw/io/SourceTest.java

fixed comment and added test for Charset detection

---

.travis.yml
pom.xml

Suppress Maven dependency download logging

---

core/src/main/java/tech/tablesaw/aggregate/Summarizer.java
core/src/test/java/tech/tablesaw/analytic/AnalyticQueryTest.java
core/src/test/java/tech/tablesaw/api/DateColumnTest.java

Remove unused code

---

beakerx/src/main/java/tech/tablesaw/beakerx/TablesawDisplayer.java

Adds support for `Column` in BeakerX. Today it just prints the `Column.toString` (column name). With this PR it will show the column in an interactive table widget just like it does for `Table` today

Show columns in BeakerX

---

saw/src/main/java/tech/tablesaw/io/saw/SawWriter.java
saw/src/test/java/tech/tablesaw/io/saw/SawStorageTest.java

Fix saw issue

---

core/src/main/java/tech/tablesaw/aggregate/AggregateFunctions.java
core/src/main/java/tech/tablesaw/api/NumericColumn.java
core/src/main/java/tech/tablesaw/columns/AbstractColumn.java
core/src/main/java/tech/tablesaw/columns/Column.java
core/src/main/java/tech/tablesaw/columns/numbers/NumberInterpolator.java
core/src/main/java/tech/tablesaw/interpolation/Interpolator.java
core/src/test/java/tech/tablesaw/columns/numbers/NumberInterpolatorTest.java
core/src/test/java/tech/tablesaw/interpolation/InterpolatorTest.java

Closes https://github.com/jtablesaw/tablesaw/issues/663 https://github.com/jtablesaw/tablesaw/issues/401
Added unit tests

Add interpolation methods

---

core/src/main/java/tech/tablesaw/api/Table.java
core/src/test/java/tech/tablesaw/TestData.java
core/src/test/java/tech/tablesaw/examples/Example1.java

Closes https://github.com/jtablesaw/tablesaw/issues/667

Replace Airframe with Tablesaw in JavaDocs

---

docs-src/dist/gettingstarted.md
docs-src/main/gettingstarted.md
docs/gettingstarted.md

Deploying docs. Copy from docs-src/ to docs/

Deploy getting started docs updates

---

docs/userguide/mapping.md

Updated the documentation for Custom map functions to match the current code base
No unit test. Documentation change.

#694 update documentation for Custom map functions

---

jsplot/src/main/java/tech/tablesaw/plotly/traces/HistogramTrace.java
jsplot/src/main/resources/trace_template.html
jsplot/src/test/java/tech/tablesaw/examples/HistogramFuncExample.java
jsplot/src/test/java/tech/tablesaw/examples/HistogramHorizontalExample.java
jsplot/src/test/java/tech/tablesaw/examples/HistogramProbabilityExample.java

Support for probability histograms (See issue #681) via histnorm property
Support for bin summary calculations in histograms via histfunc property
Support for rendering a histogram horizontally
Examples for each.
Existing tests work
see above
Existing tests and new example code to visually test new functionality

Enhancements to Histogram

---

docs-src/main/userguide/tables.md
docs/userguide/tables.md

Changes in file userguide/tables.md
1. Added documentation to add new Row
2. Added documentation to add new Row at certain index
3. Added documentation to remove Row
4. Added documentation to remove Row based on some criteria
Fixes #708 
Not required

Updated Tables Documentation: Section Add and remove Rows

---

core/pom.xml
core/src/main/java/tech/tablesaw/conversion/smile/SmileConverter.java
core/src/test/java/tech/tablesaw/conversion/smile/SmileConverterTest.java
docs-src/dist/userguide/ml/Moneyball Linear regression.md

Upgrades to Smile 2.0
Updated the existing unit tests. Deleted a few since there are less cases to cover now

Upgrade to Smile 2.0.0

---

core/src/test/java/tech/tablesaw/SortTest.java
core/src/test/java/tech/tablesaw/TableAssertions.java

- [ X] Tick to sign-off your agreement to the [Developer Certificate of Origin (DCO) 1.1](https://developercertificate.org)
Moved assertTablesEquals test helper into a standalone class for use in other tests and PR's
Existing SortTest continues to pass

move useful test method into a class for reuse in other tests

---

core/src/main/java/tech/tablesaw/api/QuerySupport.java
core/src/main/java/tech/tablesaw/api/Table.java
core/src/main/java/tech/tablesaw/filtering/DeferredBooleanColumn.java
core/src/main/java/tech/tablesaw/filtering/DeferredColumn.java
core/src/main/java/tech/tablesaw/filtering/DeferredDateColumn.java
core/src/main/java/tech/tablesaw/filtering/DeferredDateTimeColumn.java
core/src/main/java/tech/tablesaw/filtering/DeferredInstantColumn.java
core/src/main/java/tech/tablesaw/filtering/DeferredNumberColumn.java
core/src/main/java/tech/tablesaw/filtering/DeferredStringColumn.java
core/src/main/java/tech/tablesaw/filtering/DeferredTextColumn.java
core/src/main/java/tech/tablesaw/filtering/DeferredTimeColumn.java

Added `isMissing` and `isNotMissing` to base class
These methods are inherited, so any existing tests should test them

Allow queries on untyped columns

---

core/src/main/java/tech/tablesaw/columns/numbers/NumberMapFunctions.java
core/src/test/java/tech/tablesaw/api/NumberColumnTest.java

Added new `cumMin` and `cumMax` methods
Added new tests

Add cumMin and cumMax

---

jsplot/src/main/java/tech/tablesaw/plotly/traces/BoxTrace.java
jsplot/src/test/java/tech/tablesaw/plotly/BoxTest.java

Issue 740 (missing override method caused incorrect return type)

---

jsplot/src/main/java/tech/tablesaw/plotly/traces/Scatter3DTrace.java
jsplot/src/test/java/tech/tablesaw/plotly/Scatter3DTest.java

fixed issue in 3d scatter caused by faulty inheritance

---

docs-src/dist/userguide/tables.md
docs-src/main/userguide/tables.md
docs/userguide/tables.md

Fixed broken link in docs: Tablesaw vs tablesaw
Also adjusted the domain/host name to what is used elsewhere.
No

docs: Fix broken link (404) to importing_data.

---

core/src/main/java/tech/tablesaw/columns/AbstractColumn.java
core/src/main/java/tech/tablesaw/columns/Column.java
core/src/test/java/tech/tablesaw/columns/ColumnTest.java

Should solve #786
Added an indexOf method to all column types.
Works the same way as Java's ``List::indexOf(Object)``.
A simple test for basic behaviour was added to the ``ColumnTest`` class.

Added implementation and tests for column's indexOf method.

---

core/src/main/java/tech/tablesaw/api/ColumnType.java
core/src/test/java/tech/tablesaw/api/TableTest.java

Fix NPE in ColumnType.compare

---

core/src/main/java/tech/tablesaw/api/BooleanColumn.java
core/src/main/java/tech/tablesaw/api/DateColumn.java
core/src/main/java/tech/tablesaw/api/DateTimeColumn.java
core/src/main/java/tech/tablesaw/api/DoubleColumn.java
core/src/main/java/tech/tablesaw/api/FloatColumn.java
core/src/main/java/tech/tablesaw/api/InstantColumn.java
core/src/main/java/tech/tablesaw/api/IntColumn.java
core/src/main/java/tech/tablesaw/api/LongColumn.java
core/src/main/java/tech/tablesaw/api/ShortColumn.java
core/src/main/java/tech/tablesaw/api/StringColumn.java
core/src/main/java/tech/tablesaw/api/TextColumn.java
core/src/main/java/tech/tablesaw/api/TimeColumn.java

Handle null value in set

---

jsplot/src/main/java/tech/tablesaw/plotly/components/Config.java
jsplot/src/main/resources/config_template.html
jsplot/src/test/java/tech/tablesaw/plotly/components/ConfigTest.java

fixes #794
added a responsive attribute to config to match Plotty.
Yes

added responsive attr in config

---

saw/src/main/java/tech/tablesaw/io/saw/ColumnMetadata.java
saw/src/main/java/tech/tablesaw/io/saw/TableMetadata.java
saw/src/test/java/tech/tablesaw/io/saw/SawStorageTest.java

What was changed?
Merged from Master, added a comment, and removed unused code
No, because the change was removing unused code. Existing tests pass.

Merged from Master, added a comment, and removed unused code

---

.github/workflows/ci.yml

There's still other stuff done in the Travis file that's not done here
https://github.com/jtablesaw/tablesaw/blob/master/.travis.yml

Setup basic tests on GitHub Actions

---

docs-src/main/gettingstarted.md
docs-src/main/userguide/columns.md
docs-src/main/userguide/importing_data.md

Few broken links in documentation have been updated. #827

Fixed javadoc links #827.

---

.github/workflows/ci.yml

Java 15 is the latest version released

Java versions

---

core/src/main/java/tech/tablesaw/api/Table.java
core/src/test/java/tech/tablesaw/api/TableTest.java

implemented reordering of columns using column names (issue #863)

---

core/src/main/java/tech/tablesaw/api/Row.java
core/src/main/java/tech/tablesaw/api/Table.java
core/src/test/java/tech/tablesaw/api/TableTest.java
data/molten_smiths.csv
data/molten_smiths_drop_missing.csv

Added two operations to Table
Added getInternal() methods to Row for Boolean and Instant column types. 
yes

Beta implementation of "Tidy" Melt and Cast operations

---

jsplot/src/main/java/tech/tablesaw/plotly/Plot.java

made private members public
no

implement access level changes for Plot class

---

core/src/main/java/tech/tablesaw/index/StringIndex.java
core/src/main/java/tech/tablesaw/joining/DataFrameJoiner.java
core/src/test/java/tech/tablesaw/api/TextColumnTest.java

fix for the join issue.

---

core/src/main/java/tech/tablesaw/io/ReadOptions.java
core/src/main/java/tech/tablesaw/io/Source.java
core/src/main/java/tech/tablesaw/io/csv/CsvReadOptions.java
core/src/main/java/tech/tablesaw/io/csv/CsvReader.java

Use existing charset when available for creating reader

---

core/src/main/java/tech/tablesaw/io/TypeUtils.java
core/src/test/java/tech/tablesaw/io/csv/CsvReaderTest.java
data/missing_values2.csv

as described in title, plus a test. 
Yes

added "N/A" as a default mssing value indicator, plus test

---

core/src/main/java/tech/tablesaw/columns/numbers/NumberColumnFormatter.java

add a formatter for numbers that only sets the missing value string

---

core/src/main/java/tech/tablesaw/api/StringColumn.java
core/src/main/java/tech/tablesaw/api/TextColumn.java
core/src/test/java/tech/tablesaw/api/TextColumnTest.java

Removed parsing logic from append(). This fixes #897, but doesn't implement the enhancements considered in #913
yes.

Fix implementation of append(String) in TextColumn

---

core/pom.xml

bumped guava version for security improvements

---

core/src/test/java/tech/tablesaw/joining/DataFrameJoinerTest.java
excel/src/test/java/tech/tablesaw/io/xlsx/XlsxReaderTest.java

remove print statements in tests writing to system.out

---

jsplot/src/main/java/tech/tablesaw/plotly/Plot.java
jsplot/src/test/java/tech/tablesaw/plotly/PlotTest.java

Made it possible to open default local browser on an arbitrary HTML page, presumably incorporating one or more plots. Also made constants protected so they could be accessed from a subclass. 
yes.

implementation of enhancement issue #860

---

README.md

Added link to the tablesaw-parquet project in README
Visual inspection

Added link to the tablesaw-parquet project in README

---

core/src/main/java/tech/tablesaw/api/Table.java
core/src/main/java/tech/tablesaw/table/Relation.java
core/src/test/java/tech/tablesaw/table/TableSliceTest.java

Moved the structure implementation from Table up to Relation, replacing the existing version there.
Moved the structure implementation from Table up to Relation, replacing the existing version there.
Yes

fix issue #963

---

core/src/main/java/tech/tablesaw/table/TableSliceGroup.java

#972
- [ x] Tick to sign-off your agreement to the [Developer Certificate of Origin (DCO) 1.1](https://developercertificate.org)
No

Aggregate by non-primitive column type that extends Number

---

core/src/main/java/tech/tablesaw/api/BooleanColumn.java
core/src/main/java/tech/tablesaw/api/DateColumn.java
core/src/main/java/tech/tablesaw/api/DateTimeColumn.java
core/src/main/java/tech/tablesaw/api/DoubleColumn.java
core/src/main/java/tech/tablesaw/api/FloatColumn.java
core/src/main/java/tech/tablesaw/api/InstantColumn.java
core/src/main/java/tech/tablesaw/api/IntColumn.java
core/src/main/java/tech/tablesaw/api/LongColumn.java
core/src/main/java/tech/tablesaw/api/ShortColumn.java
core/src/main/java/tech/tablesaw/api/TextColumn.java
core/src/main/java/tech/tablesaw/api/TimeColumn.java

Made all data fields protected in the columns (except StringColumn, which is extremely complex).
Did you add a unit test? no

made all data fields protected

---

core/src/main/java/tech/tablesaw/api/DoubleColumn.java
core/src/main/java/tech/tablesaw/api/FloatColumn.java
core/src/main/java/tech/tablesaw/api/IntColumn.java
core/src/main/java/tech/tablesaw/api/ShortColumn.java
core/src/main/java/tech/tablesaw/api/Table.java
core/src/main/java/tech/tablesaw/columns/strings/StringFilters.java
core/src/test/java/tech/tablesaw/api/StringColumnTest.java
core/src/test/java/tech/tablesaw/api/TableTest.java
core/src/test/java/tech/tablesaw/columns/numbers/NumberFiltersTest.java

minor extensions to table and common APIs
yes.

Minor extensions

---

core/src/main/java/tech/tablesaw/api/BooleanColumn.java
core/src/main/java/tech/tablesaw/api/DateColumn.java
core/src/main/java/tech/tablesaw/api/DoubleColumn.java
core/src/main/java/tech/tablesaw/api/FloatColumn.java
core/src/main/java/tech/tablesaw/api/IntColumn.java
core/src/main/java/tech/tablesaw/api/LongColumn.java
core/src/main/java/tech/tablesaw/api/ShortColumn.java
core/src/main/java/tech/tablesaw/api/TimeColumn.java

added set(Selection, byte) to BooleanColumn, plus Doc cleanup on Column classes
Did you add a unit test? No. It's a straight call through to a tested method

added set(Selection, byte) to BooleanColumn, plus Doc cleanup

---

saw/src/test/java/tech/tablesaw/io/saw/SawStorageTest.java

Loaded baseball table once; reduced size of some tables tested. Eliminated one very large test

made saw tests run faster, no loss of coverage

---

core/pom.xml
jsplot/pom.xml
saw/pom.xml

as described in the title.
I don't think this plugin is used, but this might need to be reverted if i'm wrong
No

removed the shaded jar plugin from the saw, jsplot, and core poms

---

core/pom.xml

upgrade roaring bitmaps to 0.9.25

---

pom.xml

replacing dependabot upgrade PR 

update pom with new Jackson versions

---

docs-src/pom.xml
excel/pom.xml
html/pom.xml
json/pom.xml

remove shade plugins

---

core/src/main/java/tech/tablesaw/api/NumberColumn.java
core/src/test/java/tech/tablesaw/api/NumberColumnTest.java

modified method to ensure that the ColumnType was set in the formatter

fix for issue #1047 : setPrintFormatter causes NPE, plus test

---

excel/pom.xml

as described above. Eliminating a transitive security vulnerability warning in unused apache commons-compress library, pulled in by the poi library. 
Did you add a unit test? No.

Update pom.xml to upgrade apache poi-ooxml 

---

core/src/main/java/tech/tablesaw/api/BooleanColumn.java
core/src/main/java/tech/tablesaw/api/InstantColumn.java
core/src/main/java/tech/tablesaw/api/Table.java
core/src/main/java/tech/tablesaw/columns/numbers/LongColumnType.java
core/src/main/java/tech/tablesaw/table/TableSlice.java

fixed remaining javadoc warnings

---

.github/workflows/ci.yml
pom.xml

consider adding 18 soon
as described above

upgrade jdk to 11 and update CI builds to use 11 and 17

---

saw/pom.xml
saw/src/main/java/tech/tablesaw/io/saw/CompressionType.java
saw/src/main/java/tech/tablesaw/io/saw/SawMetadata.java
saw/src/main/java/tech/tablesaw/io/saw/SawReader.java
saw/src/main/java/tech/tablesaw/io/saw/SawWriter.java
saw/src/test/java/tech/tablesaw/io/saw/SawMetadataTest.java
saw/src/test/java/tech/tablesaw/io/saw/SawStorageTest.java

- [ x] Tick to sign-off your agreement to the [Developer Certificate of Origin (DCO) 1.1](https://developercertificate.org)
Introduced LZ4 compression as an option for saw storage
Did you add a unit test?  Yes.

introduce LZ4 compression option

---

core/src/main/java/tech/tablesaw/api/InstantColumn.java
core/src/main/java/tech/tablesaw/api/TextColumn.java
core/src/main/java/tech/tablesaw/columns/instant/PackedInstant.java
core/src/main/java/tech/tablesaw/columns/strings/ByteDictionaryMap.java
core/src/main/java/tech/tablesaw/columns/strings/IntDictionaryMap.java
core/src/main/java/tech/tablesaw/columns/strings/ShortDictionaryMap.java
core/src/test/java/tech/tablesaw/io/csv/CsvReaderTest.java

Cleaned up a few todos, other cosmetic changes

---

core/src/main/java/tech/tablesaw/selection/BitSetBackedSelection.java
core/src/test/java/tech/tablesaw/selection/BitSetSelectionTest.java

Added test for interoperability between Selection implementations

---

docs/userguide/ml/Heart Random forest.md
docs/userguide/ml/Introduction.md
docs/userguide/ml/Uber K Means.md

Smile Tutorial links were corrected and individually tested based on conversation with @lwhite1 
Light updates made to introduction.md

Fix tutorial links

---

core/src/main/java/tech/tablesaw/columns/numbers/DoubleParser.java
core/src/test/java/tech/tablesaw/api/DoubleParserTest.java

- Yes, appended to the `tech.tablesaw.api.DoubleParserTest` class

Double Parser Issue Fix (#1132)

---

pom.xml

Upgrade Maven plugins

---

core/pom.xml

Upgrade h2 database to solve dependabot warning

---

core/pom.xml

Upgrades Smile from 2.0.0 -> 2.6.0
Yes

Upgrades Smile from 2.0.0 -> 2.6.0

---

core/src/main/java/tech/tablesaw/columns/AbstractColumn.java
core/src/main/java/tech/tablesaw/columns/Column.java
core/src/test/java/tech/tablesaw/columns/ColumnTest.java

Adds a new method `lastIndexOf` in `Column` to find the last index of a given occurence in a column. It comes in addition to `indexOf`. I find it usefull, especialy when working with time series.
Comes with a unit test similar to what exists for `indexOf`.

Find last index of element in column

---

json/pom.xml

Cherry pick of [50cb481](https://github.com/jtablesaw/tablesaw/commit/50cb481718ff07c4d0b33c7b97d6bec0a5f4dccc) onto master branch
Did you add a unit test? No since this is dependency upgrade so no new unit test case is required.

Upgrading json-flattener version to latest 0.16.4 version

---

core/pom.xml

chore: upgrade guava

---

.github/workflows/ci.yml

chore: test against newer version of Java

---

jsplot/src/main/java/tech/tablesaw/plotly/components/Layout.java

Correct DEFAULT_HOVER_MODE to CLOSEST

---

pom.xml

closes https://github.com/jtablesaw/tablesaw/issues/1277

Update Maven formatting plugin

---

arrow/pom.xml

chore: bump arrow-memory-netty
